import jsPDF from 'jspdf';
import { EMRProfile } from '@/types/emr';
import { HealthRecord } from '@/types/prescription';

export interface CompiledMedication {
  id?: string;
  name: string;
  dosage?: string;
  frequency?: string;
  timing?: string;
  doctorName?: string;
  instructions?: string;
}

/**
 * Generates a clean, professional Emergency Medical Record (EMR) PDF document.
 * Includes Patient Metrics, Allergies, Conditions, Active Medications,
 * Hospital Records, and full AI Clinical Synthesis Report when provided.
 */
export function generateEMRPdfDocument(
  profile: EMRProfile | null,
  compiledMeds: CompiledMedication[] = [],
  aiReport?: string | null,
  healthRecords: HealthRecord[] = []
): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let currentY = 16;

  const renderFooter = (pageNumber: number, totalPages: number) => {
    const footerY = 286;
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, footerY - 4, pageWidth - margin, footerY - 4);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(
      'CONFIDENTIAL MEDICAL RECORD • Generated by Prescriptime for clinical, emergency and patient review.',
      margin,
      footerY
    );
    doc.text(
      `Page ${pageNumber} of ${totalPages}  •  prescriptime.health`,
      pageWidth - margin,
      footerY,
      { align: 'right' }
    );
  };

  const checkPageBreak = (neededHeight: number): void => {
    if (currentY + neededHeight > pageHeight - 20) {
      doc.addPage();
      currentY = 20;
    }
  };

  // Header Banner: Deep Medical Blue
  doc.setFillColor(15, 88, 182); // #0F58B6
  doc.roundedRect(margin, currentY, contentWidth, 24, 3, 3, 'F');

  // Brand / Document Title inside Header
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('PRESCRIPTIME • EMERGENCY MEDICAL RECORD (EMR)', margin + 6, currentY + 9);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(220, 235, 255);
  doc.text(
    'CRITICAL LIFE-SAFETY MEDICAL INFORMATION & ACTIVE PRESCRIPTIONS',
    margin + 6,
    currentY + 16
  );

  const printDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
  doc.setFontSize(8);
  doc.text(`DATE: ${printDate}`, pageWidth - margin - 6, currentY + 16, { align: 'right' });

  currentY += 30;

  // Patient Card Section
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(margin, currentY, contentWidth, 34, 3, 3, 'FD');

  // Patient Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text(profile?.fullName || 'Not Specified', margin + 6, currentY + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`DOB: ${profile?.dateOfBirth || 'Not specified'}`, margin + 6, currentY + 18);

  // Blood Group Pill (Top-right inside patient card)
  const bg = profile?.bloodGroup || 'Unknown';
  const bgBoxWidth = 32;
  const bgBoxX = pageWidth - margin - bgBoxWidth - 6;
  doc.setFillColor(254, 242, 242); // rose-50
  doc.setDrawColor(244, 63, 94); // rose-500
  doc.roundedRect(bgBoxX, currentY + 6, bgBoxWidth, 20, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(190, 18, 60); // rose-700
  doc.text('BLOOD GROUP', bgBoxX + bgBoxWidth / 2, currentY + 12, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(159, 18, 57); // rose-900
  doc.text(bg, bgBoxX + bgBoxWidth / 2, currentY + 21, { align: 'center' });

  // Emergency Contact Info
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text('Emergency Contact: ', margin + 6, currentY + 27);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);
  const contactText = `${profile?.emergencyContactName || 'None'}  |  Tel: ${
    profile?.emergencyContactPhone || 'Not set'
  }`;
  doc.text(contactText, margin + 40, currentY + 27);

  currentY += 40;

  // Clinical Alerts: Allergies & Active Conditions (2 columns)
  const colWidth = (contentWidth - 4) / 2;

  // Allergies Box
  doc.setFillColor(255, 251, 235); // amber-50
  doc.setDrawColor(245, 158, 11); // amber-500
  doc.roundedRect(margin, currentY, colWidth, 24, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(180, 83, 9); // amber-700
  doc.text('KNOWN DRUG & FOOD ALLERGIES', margin + 4, currentY + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  const allergies = profile?.allergies?.trim() || 'None reported';
  doc.text(allergies, margin + 4, currentY + 15, { maxWidth: colWidth - 8 });

  // Active Conditions Box
  const col2X = margin + colWidth + 4;
  doc.setFillColor(250, 245, 255); // purple-50
  doc.setDrawColor(168, 85, 247); // purple-500
  doc.roundedRect(col2X, currentY, colWidth, 24, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(126, 34, 206); // purple-700
  doc.text('CURRENT ACTIVE CONDITIONS', col2X + 4, currentY + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  const conditions = profile?.activeConditions?.trim() || 'None reported';
  doc.text(conditions, col2X + 4, currentY + 15, { maxWidth: colWidth - 8 });

  currentY += 30;

  // Active Medications Section Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(15, 88, 182);
  doc.text(`CURRENT ACTIVE MEDICATIONS (${compiledMeds.length} Verified from Rx Cabinet)`, margin, currentY);

  // Horizontal divider
  doc.setDrawColor(203, 213, 225); // slate-300
  doc.line(margin, currentY + 2, pageWidth - margin, currentY + 2);
  currentY += 8;

  if (compiledMeds.length === 0) {
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, currentY, contentWidth, 14, 2, 2, 'FD');
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text('No active prescribed medications currently listed.', margin + 6, currentY + 9);
    currentY += 20;
  } else {
    compiledMeds.forEach((med, idx) => {
      checkPageBreak(18);

      doc.setFillColor(idx % 2 === 0 ? 255 : 248, idx % 2 === 0 ? 255 : 250, idx % 2 === 0 ? 255 : 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(margin, currentY, contentWidth, 15, 1.5, 1.5, 'FD');

      // Medicine Name
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(15, 23, 42);
      doc.text(`${idx + 1}. ${med.name}`, margin + 4, currentY + 6);

      // Dosage & Frequency
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105); // slate-600
      const timingStr = med.timing ? med.timing.replace('_', ' ') : 'Anytime';
      const detailStr = `Dosage: ${med.dosage || 'Standard'}  •  Routine: ${med.frequency || 'OD'}  •  Timing: ${timingStr}`;
      doc.text(detailStr, margin + 4, currentY + 11.5);

      // Prescriber (Right aligned)
      if (med.doctorName) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text(`Dr. ${med.doctorName.replace(/^dr\.?\s*/i, '')}`, pageWidth - margin - 4, currentY + 8.5, {
          align: 'right',
        });
      }

      currentY += 18;
    });
  }

  // Hospital & Diagnostic Records (if any)
  if (healthRecords.length > 0) {
    checkPageBreak(30);
    currentY += 6;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 88, 182);
    doc.text(`HOSPITAL & DIAGNOSTIC RECORDS (${healthRecords.length} Attached)`, margin, currentY);

    doc.setDrawColor(203, 213, 225);
    doc.line(margin, currentY + 2, pageWidth - margin, currentY + 2);
    currentY += 8;

    healthRecords.forEach((hr, idx) => {
      checkPageBreak(16);

      doc.setFillColor(250, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(margin, currentY, contentWidth, 14, 1.5, 1.5, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      doc.text(`[${hr.categoryLabel}] ${hr.title}`, margin + 4, currentY + 5.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      const subInfo = `Date: ${hr.date || 'N/A'}  •  Facility: ${hr.clinicOrHospital || 'Clinic'}  •  ${hr.diagnosisOrTest || ''}`;
      doc.text(subInfo, margin + 4, currentY + 10.5);

      currentY += 16;
    });
  }

  // Full AI Clinical Synthesis Report (when present)
  if (aiReport && aiReport.trim().length > 0) {
    // Start AI Clinical Report on a clean page or clear section
    doc.addPage();
    currentY = 18;

    // AI Header Banner
    doc.setFillColor(238, 242, 255); // indigo-50
    doc.setDrawColor(199, 210, 254); // indigo-200
    doc.roundedRect(margin, currentY, contentWidth, 18, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(49, 46, 129); // indigo-900
    doc.text('✦ AI CLINICAL SYNTHESIS & HEALTH ANALYSIS REPORT', margin + 5, currentY + 7.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(79, 70, 229); // indigo-600
    doc.text(
      'Automated reconciliation computed strictly from verified prescriptions and clinical records.',
      margin + 5,
      currentY + 13.5
    );

    currentY += 24;

    // Split markdown lines
    const rawLines = aiReport.split(/\r?\n/);

    for (let i = 0; i < rawLines.length; i++) {
      const line = rawLines[i].trim();
      if (!line) {
        currentY += 3;
        continue;
      }

      // Section Headings (e.g. ### 1. Executive Summary or **1. Heading**)
      if (line.startsWith('#') || (line.startsWith('**') && line.endsWith('**') && line.length < 60)) {
        checkPageBreak(18);
        currentY += 4;

        const headingText = line.replace(/^[#*\s]+|[#*\s]+$/g, '');

        doc.setFillColor(241, 245, 249); // slate-100
        doc.setDrawColor(203, 213, 225);
        doc.roundedRect(margin, currentY - 1, contentWidth, 8, 1, 1, 'FD');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9.5);
        doc.setTextColor(15, 88, 182); // blue-700
        doc.text(headingText, margin + 4, currentY + 5);

        currentY += 11;
        continue;
      }

      // Bullet points (e.g. * Patient Name: ... or - Item)
      if (line.startsWith('*') || line.startsWith('-') || line.startsWith('•')) {
        const cleanedBullet = line.replace(/^[*•\-]\s*/, '');
        const cleanContent = cleanedBullet.replace(/\*\*/g, ''); // strip markdown bold syntax for clean text

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(30, 41, 59); // slate-800

        const wrapped = doc.splitTextToSize(cleanContent, contentWidth - 10);
        checkPageBreak(wrapped.length * 4.5 + 2);

        // Draw bullet point
        doc.setFillColor(15, 88, 182);
        doc.circle(margin + 4, currentY + 2.5, 0.8, 'F');

        doc.text(wrapped, margin + 8, currentY + 3.5);
        currentY += wrapped.length * 4.5 + 1.5;
        continue;
      }

      // Standard text / paragraphs
      const cleanParagraph = line.replace(/\*\*/g, '');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(51, 65, 85); // slate-700

      const wrapped = doc.splitTextToSize(cleanParagraph, contentWidth);
      checkPageBreak(wrapped.length * 4.5 + 2);

      doc.text(wrapped, margin, currentY + 3.5);
      currentY += wrapped.length * 4.5 + 2;
    }
  }

  // Stamp footer on every page
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    renderFooter(p, totalPages);
  }

  return doc;
}

/**
 * Creates a File instance from the generated PDF for Web Share API
 */
export function createEMRPdfFile(
  profile: EMRProfile | null,
  compiledMeds: CompiledMedication[] = [],
  aiReport?: string | null,
  healthRecords: HealthRecord[] = []
): File {
  const doc = generateEMRPdfDocument(profile, compiledMeds, aiReport, healthRecords);
  const pdfBlob = doc.output('blob');
  const safeName = (profile?.fullName || 'Patient').replace(/[^a-zA-Z0-9_-]/g, '_');
  const fileName = `Prescriptime_EMR_${safeName}.pdf`;

  return new File([pdfBlob], fileName, { type: 'application/pdf' });
}

