'use client';

import React, { useState, useCallback, useRef, useEffect } from 'react';
import {
  Upload,
  X,
  AlertTriangle,
  CheckCircle2,
  ShieldAlert,
  FileText,
  Info,
  Activity,
  FileSearch,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  Hospital,
  Pill,
  ShieldCheck,
  Check,
  Calendar,
  User,
  Camera,
  SwitchCamera,
  FlipHorizontal,
} from 'lucide-react';
import { extractTextFromDocument, getPdfFirstPagePreview, compressImageForUpload } from '@/lib/ocr';
import { ExtractedData, Prescription, DocumentClassification, HealthRecord, FamilyMemberRelation } from '@/types/prescription';
import { OCRScanProgress } from './OCRScanProgress';
import { ExtractionReviewModal } from './ExtractionReviewModal';
import { FamilyMemberSelector } from './FamilyMemberSelector';
import { PrescriptionDiffView } from '../organizer/PrescriptionDiffView';
import { comparePrescriptions, PrescriptionDiffResult } from '@/lib/prescriptionDiff';
import { 
  savePrescription, 
  saveHealthRecord, 
  getStoredPrescriptions,
  autoGenerateDoctorVisitForPrescription,
  autoGenerateDoctorVisitForHealthRecord
} from '@/lib/storage';
import { saveStoredFile } from '@/lib/fileStorage';
import confetti from 'canvas-confetti';
import { useBodyScrollLock } from '@/lib/useBodyScrollLock';
import { useAuth } from '@/context/AuthContext';

interface DocumentUploadModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess?: (prescription?: Prescription, record?: HealthRecord) => void;
}

export const DocumentUploadModal: React.FC<DocumentUploadModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
}) => {
  useBodyScrollLock(isOpen);
  const { user } = useAuth();

  const [step, setStep] = useState<
    'upload' | 'camera' | 'scanning' | 'extracting' | 'classified_notice' | 'review' | 'diff' | 'success'
  >('upload');
  const [uploadCategoryHint, setUploadCategoryHint] = useState<'all' | 'prescription' | 'hospital_record'>('all');
  const [diffData, setDiffData] = useState<{
    oldRx: Prescription;
    newRx: Prescription;
    diffResult: PrescriptionDiffResult;
  } | null>(null);
  const [dragOver, setDragOver] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string>('');
  const [persistentBase64, setPersistentBase64] = useState<string>('');
  const [scanProgress, setScanProgress] = useState(0);
  const [statusMessage, setStatusMessage] = useState('');
  const [error, setError] = useState<string>('');
  const [isValidationError, setIsValidationError] = useState(false);
  const [classificationResult, setClassificationResult] = useState<DocumentClassification | null>(null);
  const [extractedData, setExtractedData] = useState<ExtractedData | null>(null);
  const [extractedRawText, setExtractedRawText] = useState<string>('');
  const [showRawText, setShowRawText] = useState(false);
  const [successMessage, setSuccessMessage] = useState<string>('Document Verified & Saved!');

  // Hospital Record Family Member Tagging State
  const [hrFamilyMember, setHrFamilyMember] = useState<FamilyMemberRelation>('self');
  const [hrPatientName, setHrPatientName] = useState<string>('');
  const [hrCustomRelation, setHrCustomRelation] = useState<string>('');

  // Camera Capture States & Refs
  const [cameraStream, setCameraStream] = useState<MediaStream | null>(null);
  const [facingMode, setFacingMode] = useState<'environment' | 'user'>('environment');
  const [cameraError, setCameraError] = useState<string>('');
  const videoRef = useRef<HTMLVideoElement>(null);
  const nativeCameraInputRef = useRef<HTMLInputElement>(null);

  const stopCamera = useCallback(() => {
    if (cameraStream) {
      cameraStream.getTracks().forEach((track) => track.stop());
      setCameraStream(null);
    }
  }, [cameraStream]);

  useEffect(() => {
    return () => {
      stopCamera();
    };
  }, [stopCamera]);

  const startCamera = async (mode: 'environment' | 'user' = facingMode) => {
    setCameraError('');
    if (cameraStream) {
      cameraStream.getTracks().forEach((track) => track.stop());
      setCameraStream(null);
    }
    setStep('camera');
    try {
      if (typeof navigator === 'undefined' || !navigator.mediaDevices?.getUserMedia) {
        throw new Error('In-browser camera stream not supported. You can use your device native camera or file browser.');
      }
      const stream = await navigator.mediaDevices.getUserMedia({
        video: {
          facingMode: { ideal: mode },
          width: { ideal: 1920 },
          height: { ideal: 1080 },
        },
        audio: false,
      });
      setCameraStream(stream);
      setFacingMode(mode);
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.play().catch(() => {});
      }
    } catch (err: any) {
      console.warn('Camera access error:', err);
      setCameraError(err.message || 'Unable to access device camera. Please check camera permissions.');
    }
  };

  const toggleFacingMode = () => {
    const nextMode = facingMode === 'environment' ? 'user' : 'environment';
    startCamera(nextMode);
  };

  const capturePhoto = () => {
    if (!videoRef.current) return;
    const video = videoRef.current;
    const canvas = document.createElement('canvas');
    canvas.width = video.videoWidth || 1280;
    canvas.height = video.videoHeight || 720;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);

    canvas.toBlob(
      (blob) => {
        if (!blob) return;
        const capturedFile = new File([blob], `camera-doc-${Date.now()}.jpg`, {
          type: 'image/jpeg',
          lastModified: Date.now(),
        });
        stopCamera();
        processFile(capturedFile);
      },
      'image/jpeg',
      0.95
    );
  };

  const resetState = useCallback(() => {
    stopCamera();
    setStep('upload');
    setSelectedFile(null);
    setPreviewUrl('');
    setPersistentBase64('');
    setScanProgress(0);
    setStatusMessage('');
    setError('');
    setIsValidationError(false);
    setClassificationResult(null);
    setExtractedData(null);
    setExtractedRawText('');
    setShowRawText(false);
    setCameraError('');
    setHrFamilyMember('self');
    setHrPatientName('');
    setHrCustomRelation('');
  }, [stopCamera]);

  const handleClose = () => {
    resetState();
    onClose();
  };

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  };

  const processTextWithAPI = async (
    rawText: string,
    fileName: string,
    imageBase64?: string,
    mimeType?: string,
    retryCount = 0
  ) => {
    setStep('extracting');
    setStatusMessage('Analyzing document structure, clinical entities & medical validity...');
    setScanProgress(88);

    let response: Response;
    try {
      response = await fetch('/api/extract', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          raw_text: rawText,
          image_base64: imageBase64,
          mime_type: mimeType,
          document_type_hint: uploadCategoryHint === 'hospital_record' ? 'diagnostic_report' : 'prescription',
        }),
      });
    } catch (networkErr: any) {
      throw new Error(`Network error during clinical analysis: ${networkErr.message || 'Please check your connection.'}`);
    }

    // 1. Safe detection of HTTP 413 (Payload Too Large) with automatic self-healing retry
    if (response.status === 413) {
      if (imageBase64 && rawText && rawText.trim().length > 30 && retryCount === 0) {
        console.warn('Document payload exceeded server limit (413). Retrying with extracted clinical text only...');
        setStatusMessage('Large document detected. Processing extracted clinical report text...');
        return processTextWithAPI(rawText, fileName, undefined, undefined, 1);
      }
      throw new Error('The uploaded document is too large for cloud analysis. Please try uploading an optimized or smaller PDF.');
    }

    // 2. Safe response parsing (never call response.json() blindly on non-JSON/HTML error pages)
    let result: any = null;
    const contentType = response.headers.get('content-type') || '';
    if (contentType.includes('application/json')) {
      try {
        result = await response.json();
      } catch (jsonErr) {
        console.warn('Failed to parse JSON response:', jsonErr);
      }
    } else {
      const errorText = await response.text().catch(() => '');
      throw new Error(errorText || `Server returned unexpected status ${response.status}`);
    }

    if (!result) {
      throw new Error('Server returned an empty or invalid clinical response.');
    }

    const classification: DocumentClassification | undefined =
      result.classification || result.extracted_data?.classification;

    // Strict Non-Medical Block
    if (!response.ok || !result.success) {
      if (classification && !classification.isHealthcare) {
        setClassificationResult(classification);
        setError(
          result.error ||
            'Wrong file: The uploaded document is not a healthcare or medical record. Only official medical files are accepted.'
        );
        setIsValidationError(true);
        setStep('classified_notice');
        return;
      }

      if (classification) {
        setClassificationResult(classification);
        setExtractedData(result.extracted_data || null);
        setError(result.error || '');
        setIsValidationError(true);
        setStep('classified_notice');
        return;
      }

      setIsValidationError(!!result.isValidationError);
      throw new Error(result.error || 'Failed to extract structured clinical data.');
    }

    setScanProgress(100);
    setClassificationResult(classification || null);
    setExtractedData(result.extracted_data);
    if (result.extracted_data?.patient_name) {
      setHrPatientName(result.extracted_data.patient_name);
    }

    // If it is an active prescription with extracted medicines, show prescription review
    if (result.isPrescription && result.extracted_data?.medications?.length > 0) {
      setStep('review');
    } else {
      // It is a valid hospital record (lab report, radiology scan, discharge summary, etc.)
      // Transition to Hospital Record User Acceptance step
      setStep('classified_notice');
    }
  };

  const processFile = async (file: File) => {
    setError('');
    setIsValidationError(false);

    const validTypes = ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf'];
    if (!validTypes.includes(file.type)) {
      setError('Invalid file type. Please upload a valid medical image (JPEG, PNG, WebP) or PDF.');
      setIsValidationError(true);
      return;
    }

    if (file.size > 20 * 1024 * 1024) {
      setError('File size exceeds the 20MB limit.');
      setIsValidationError(true);
      return;
    }

    setSelectedFile(file);
    const objectUrl = URL.createObjectURL(file);
    setPreviewUrl(objectUrl);

    setStep('scanning');
    setStatusMessage('Reading medical document and extracting text...');
    setScanProgress(15);

    try {
      // 1. Convert to persistent base64 data URL for cross-device view & print
      let originalBase64 = '';
      try {
        originalBase64 = await fileToBase64(file);
        setPersistentBase64(originalBase64);
      } catch (err) {
        console.warn('Base64 conversion failed:', err);
      }

      // 2. Client-side OCR / PDF text extraction
      let rawText = '';
      try {
        rawText = await extractTextFromDocument(file, (progress) => {
          setScanProgress(Math.min(85, Math.round(progress * 85)));
          if (progress > 0.3 && progress < 0.8) {
            setStatusMessage('Analyzing clinical terms, doctor orders & lab parameters...');
          }
        });
        setExtractedRawText(rawText);
      } catch (ocrErr) {
        console.warn('OCR fallback directly to AI Vision:', ocrErr);
      }

      // 3. Optimize payload for API transmission:
      // - For PDFs (multi-page, e.g. 12 pages): If text was extracted, do NOT send 15MB base64!
      //   Instead, send rawText plus a compact lightweight first-page preview (< 150KB) for vision letterhead detection.
      // - For images > 2MB: Compress/downscale to prevent hitting 413 limits.
      let apiBase64: string | undefined = undefined;
      let apiMimeType: string | undefined = file.type;

      if (file.type === 'application/pdf') {
        if (rawText && rawText.trim().length > 30) {
          // Attempt to get a lightweight 1st page preview image (< 150KB)
          const pagePreview = await getPdfFirstPagePreview(file);
          if (pagePreview) {
            apiBase64 = pagePreview;
            apiMimeType = 'image/jpeg';
          } else {
            apiBase64 = undefined; // Text-only is sufficient and ultra-fast
          }
        } else {
          // Scanned PDF with no direct selectable text: get 1st page preview
          const pagePreview = await getPdfFirstPagePreview(file);
          apiBase64 = pagePreview || (originalBase64.length < 3 * 1024 * 1024 ? originalBase64 : undefined);
          apiMimeType = pagePreview ? 'image/jpeg' : file.type;
        }
      } else if (file.type.startsWith('image/')) {
        if (file.size > 2 * 1024 * 1024) {
          apiBase64 = await compressImageForUpload(file);
          apiMimeType = 'image/jpeg';
        } else {
          apiBase64 = originalBase64 || undefined;
        }
      }

      await processTextWithAPI(rawText, file.name, apiBase64, apiMimeType);
    } catch (err: any) {
      console.error('Processing failed:', err);
      setError(err.message || 'Failed to process document');
      setStep('upload');
    }
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (file) processFile(file);
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) processFile(file);
  };

  // Prescription Review Confirmation
  const handleConfirmReview = (finalData: ExtractedData) => {
    const today = new Date().toISOString().split('T')[0];
    const nowIso = new Date().toISOString();

    const newPrescription: Prescription = {
      id: `rx-${Date.now()}`,
      title: `${finalData.diagnosis || 'Prescription'} (${finalData.doctor_name || 'Physician'})`,
      doctorName: finalData.doctor_name || 'Treating Physician',
      clinicOrHospital: finalData.clinic_or_hospital || 'Medical Center',
      patientName: finalData.patient_name || undefined,
      familyMember: finalData.family_member || 'self',
      patientRelation: finalData.patient_relation || undefined,
      date: finalData.date || today,
      uploadedAt: nowIso,
      diagnosis: finalData.diagnosis || 'General Clinical Consultation',
      medications: finalData.medications,
      notes: finalData.notes,
      followUpDate: finalData.follow_up_date,
      fileName: selectedFile?.name || 'Uploaded-Prescription.pdf',
      fileType: selectedFile?.type === 'application/pdf' ? 'pdf' : 'image',
      fileSize: selectedFile?.size || 1024 * 45,
      fileUrl: persistentBase64 || previewUrl || undefined,
      createdAt: nowIso,
      status: 'active',
      userId: user?.uid || undefined,
    };

    const previousPrescriptions = getStoredPrescriptions();
    const latestPrevious = previousPrescriptions.length > 0 ? previousPrescriptions[0] : null;
    savePrescription(newPrescription, user?.uid || undefined);
    autoGenerateDoctorVisitForPrescription(newPrescription.id, user?.uid || undefined);

    // Guarantee full-fidelity scan is stored immediately in IndexedDB
    if (persistentBase64) {
      saveStoredFile(newPrescription.id, persistentBase64).catch(() => {});
    } else if (selectedFile) {
      fileToBase64(selectedFile).then((b64) => {
        if (b64) saveStoredFile(newPrescription.id, b64).catch(() => {});
      }).catch(() => {});
    }

    if (latestPrevious && latestPrevious.id !== newPrescription.id) {
      const diff = comparePrescriptions(latestPrevious, newPrescription);
      if (diff.added.length > 0 || diff.removed.length > 0 || diff.changed.length > 0) {
        setDiffData({
          oldRx: latestPrevious,
          newRx: newPrescription,
          diffResult: diff,
        });
        setStep('diff');
        return;
      }
    }

    setSuccessMessage('Prescription Verified & Routine Scheduled!');
    setStep('success');

    try {
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#00A8FF', '#10b981', '#0F58B6'],
      });
    } catch {}

    setTimeout(() => {
      if (onSuccess) onSuccess(newPrescription);
      handleClose();
    }, 1500);
  };

  // Hospital Record User Acceptance Confirmation
  const handleAcceptHospitalRecord = () => {
    const safeClassification = classificationResult || {
      documentType: 'other_medical',
      categoryLabel: 'Hospital Record',
      verdictSummary: 'Clinical record accepted.',
      keyIndicators: [],
      isHealthcare: true,
      confidence: 0.95,
      detectedEntities: {},
    };

    const today = new Date().toISOString().split('T')[0];
    const nowIso = new Date().toISOString();

    const title =
      extractedData?.diagnosis_or_test ||
      extractedData?.diagnosis ||
      `${safeClassification.categoryLabel} (${extractedData?.clinic_or_hospital || 'Medical Facility'})`;

    const newRecord: HealthRecord = {
      id: `hr-${Date.now()}`,
      title,
      documentType: (safeClassification.documentType as any) || 'other_medical',
      categoryLabel: safeClassification.categoryLabel || 'Hospital Record',
      doctorName: extractedData?.doctor_name,
      clinicOrHospital: extractedData?.clinic_or_hospital,
      patientName: hrPatientName.trim() || extractedData?.patient_name || undefined,
      familyMember: hrFamilyMember,
      patientRelation: hrFamilyMember === 'other' ? hrCustomRelation.trim() : undefined,
      date: extractedData?.date || today,
      uploadedAt: nowIso,
      diagnosisOrTest: extractedData?.diagnosis_or_test || extractedData?.diagnosis,
      summary: extractedData?.notes || safeClassification.verdictSummary,
      keyIndicators: safeClassification.keyIndicators || [],
      rawText: extractedRawText,
      fileUrl: persistentBase64 || previewUrl || undefined,
      fileName: selectedFile?.name || 'medical_record',
      fileType: selectedFile?.type === 'application/pdf' ? 'pdf' : 'image',
      fileSize: selectedFile?.size,
      createdAt: nowIso,
      status: 'active',
      userId: user?.uid || undefined,
    };

    saveHealthRecord(newRecord, user?.uid || undefined);
    autoGenerateDoctorVisitForHealthRecord(newRecord.id, user?.uid || undefined);

    // Guarantee full-fidelity scan is stored immediately in IndexedDB
    if (persistentBase64) {
      saveStoredFile(newRecord.id, persistentBase64).catch(() => {});
    } else if (selectedFile) {
      fileToBase64(selectedFile).then((b64) => {
        if (b64) saveStoredFile(newRecord.id, b64).catch(() => {});
      }).catch(() => {});
    }

    setSuccessMessage('Hospital Record Accepted & Saved!');
    setStep('success');

    try {
      confetti({
        particleCount: 70,
        spread: 60,
        origin: { y: 0.6 },
        colors: ['#10b981', '#0F58B6', '#00A8FF'],
      });
    } catch {}

    setTimeout(() => {
      if (onSuccess) onSuccess(undefined, newRecord);
      handleClose();
    }, 1500);
  };

  const getBadgeColorClasses = (color?: string) => {
    switch (color) {
      case 'amber':
        return 'bg-amber-500/10 text-amber-700 border-amber-500/30';
      case 'cyan':
        return 'bg-blue-500/10 text-blue-700 border-blue-500/30';
      case 'emerald':
        return 'bg-emerald-500/10 text-emerald-700 border-emerald-500/30';
      case 'rose':
        return 'bg-rose-500/10 text-rose-700 border-rose-500/30';
      default:
        return 'bg-blue-50 text-blue-700 border-blue-200';
    }
  };

  const activeClassification: DocumentClassification = classificationResult || {
    isHealthcare: true,
    isPrescription: false,
    documentType: 'other_medical',
    categoryLabel: 'Hospital Record',
    confidence: 0.95,
    verdictSummary: 'Clinical documentation identified.',
    keyIndicators: [],
    guidance: 'Verify and accept clinical details.',
    detectedEntities: { medicationCount: 0 },
    badgeColor: 'cyan',
  };

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-900/65 backdrop-blur-sm animate-in fade-in duration-200 overflow-hidden overscroll-contain"
      data-lenis-prevent="true"
    >
      <div
        id="document-upload-modal"
        className="relative w-full max-w-2xl h-[90vh] max-h-[90vh] flex flex-col rounded-3xl bg-white border border-slate-200 shadow-2xl overflow-hidden text-slate-900"
        data-lenis-prevent="true"
      >
        {/* Close Button */}
        {step !== 'review' && (
          <button
            id="close-upload-modal-btn"
            onClick={handleClose}
            className="absolute top-4 right-4 sm:top-5 sm:right-5 p-2 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors z-20"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        )}

        {/* STEP: DIFF VIEW (PRESCRIPTION COMPARISON) */}
        {step === 'diff' && diffData ? (
          <PrescriptionDiffView
            oldRx={diffData.oldRx}
            newRx={diffData.newRx}
            diffResult={diffData.diffResult}
            onClose={() => {
              if (onSuccess) onSuccess(diffData.newRx);
              handleClose();
            }}
          />
        ) : step === 'review' && extractedData ? (
          <ExtractionReviewModal
            initialData={extractedData}
            onConfirm={handleConfirmReview}
            onCancel={resetState}
          />
        ) : (
          <>
            {/* Modal Pinned Header */}
            <div className="p-5 sm:p-6 pb-4 border-b border-slate-100 flex-shrink-0 pr-12 bg-slate-50/50">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-50 text-[#0F58B6] border border-blue-200 font-mono font-bold">
                  Healthcare &amp; Clinical Shield
                </span>
                <span className="text-[11px] font-mono text-slate-500 font-medium">Strict Medical Files Only</span>
              </div>
              <h2 className="text-lg sm:text-xl font-bold text-slate-900">Upload Healthcare Document</h2>
              <p className="text-xs text-slate-500 mt-0.5 font-medium">
                Upload prescriptions, pathology lab reports, radiology scans (X-Rays, MRI), and discharge summaries.
              </p>
            </div>

            {/* Modal Scrollable Body */}
            <div
              className="p-5 sm:p-6 overflow-y-auto overscroll-contain flex-1 min-h-0 space-y-5"
              data-lenis-prevent="true"
              onWheel={(e) => e.stopPropagation()}
            >
              {/* Error Alert */}
              {error && step === 'upload' && (
                <div
                  className={`p-4 rounded-2xl flex items-start gap-3 shadow-sm ${
                    isValidationError
                      ? 'bg-rose-50 border border-rose-200 text-rose-900'
                      : 'bg-amber-50 border border-amber-200 text-amber-900'
                  }`}
                >
                  <ShieldAlert className="w-5 h-5 flex-shrink-0 mt-0.5 text-rose-600" />
                  <div>
                    <p className="text-[11px] font-mono uppercase font-bold tracking-wider text-rose-700">
                      Medical Guard Notice
                    </p>
                    <p className="text-xs font-semibold text-slate-800 mt-0.5 leading-relaxed">{error}</p>
                  </div>
                </div>
              )}

              {/* STEP: UPLOAD */}
              {step === 'upload' && (
                <div className="space-y-4">
                  {/* Category Selector Pill Row */}
                  <div className="flex items-center gap-1.5 p-1 rounded-xl bg-slate-100 border border-slate-200 text-xs">
                    <button
                      type="button"
                      onClick={() => setUploadCategoryHint('all')}
                      className={`flex-1 py-1.5 px-2 rounded-lg font-bold transition-all ${
                        uploadCategoryHint === 'all'
                          ? 'bg-white text-[#0F58B6] shadow-sm'
                          : 'text-slate-600 hover:text-slate-900'
                      }`}
                    >
                      Auto-Detect (Any Medical)
                    </button>
                    <button
                      type="button"
                      onClick={() => setUploadCategoryHint('prescription')}
                      className={`flex-1 py-1.5 px-2 rounded-lg font-bold transition-all ${
                        uploadCategoryHint === 'prescription'
                          ? 'bg-white text-[#0F58B6] shadow-sm'
                          : 'text-slate-600 hover:text-slate-900'
                      }`}
                    >
                      Prescription
                    </button>
                    <button
                      type="button"
                      onClick={() => setUploadCategoryHint('hospital_record')}
                      className={`flex-1 py-1.5 px-2 rounded-lg font-bold transition-all ${
                        uploadCategoryHint === 'hospital_record'
                          ? 'bg-white text-[#0F58B6] shadow-sm'
                          : 'text-slate-600 hover:text-slate-900'
                      }`}
                    >
                      Hospital / Lab Records
                    </button>
                  </div>

                  {/* Drag & Drop Box */}
                  <div
                    onDragOver={(e) => {
                      e.preventDefault();
                      setDragOver(true);
                    }}
                    onDragLeave={() => setDragOver(false)}
                    onDrop={handleDrop}
                    className={`relative flex flex-col items-center justify-center p-8 sm:p-12 border-2 border-dashed rounded-2xl transition-all cursor-pointer ${
                      dragOver
                        ? 'border-[#0F58B6] bg-blue-50/50 scale-[0.99]'
                        : 'border-slate-300 bg-slate-50 hover:border-[#0F58B6] hover:bg-blue-50/20'
                    }`}
                  >
                    <input
                      type="file"
                      accept="image/jpeg,image/png,image/webp,image/gif,application/pdf"
                      onChange={handleFileSelect}
                      className="absolute inset-0 opacity-0 cursor-pointer"
                    />
                    <div className="w-14 h-14 rounded-2xl bg-blue-50 border border-blue-200 flex items-center justify-center text-[#0F58B6] mb-3 shadow-sm">
                      <Upload className="w-7 h-7" />
                    </div>
                    <p className="text-sm font-bold text-slate-900 mb-0.5 text-center">
                      Drop your medical document image or PDF here
                    </p>
                    <p className="text-xs text-slate-500 mb-4 font-medium text-center">
                      Prescriptions, Lab Reports, X-Rays, Scans (PNG, JPG, PDF up to 20MB)
                    </p>
                    <span className="px-5 py-2 rounded-xl bg-white hover:bg-slate-50 text-xs font-bold text-slate-800 border border-slate-300 shadow-sm transition-all">
                      Browse File from Device
                    </span>
                  </div>

                  {/* Strict Medical Notice */}
                  <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 flex items-start gap-2.5 text-xs text-slate-600">
                    <ShieldCheck className="w-4 h-4 text-[#0F58B6] flex-shrink-0 mt-0.5" />
                    <span>
                      <strong className="text-slate-900">Strict Medical Classification:</strong> Our AI will inspect the document. Only authentic healthcare files are accepted. You will review and accept the classified details before saving.
                    </span>
                  </div>

                  {/* Camera & Native Device Picker Row */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 pt-1">
                    <button
                      type="button"
                      onClick={() => startCamera('environment')}
                      id="upload-camera-stream-btn"
                      className="py-3 px-4 rounded-xl bg-blue-50/80 hover:bg-blue-100 border border-blue-200 text-[#0F58B6] font-bold text-xs flex items-center justify-center gap-2 transition-all shadow-sm active:scale-95"
                    >
                      <Camera className="w-4 h-4" />
                      <span>Take Photo (Front/Back Camera)</span>
                    </button>

                    <button
                      type="button"
                      onClick={() => nativeCameraInputRef.current?.click()}
                      id="upload-native-camera-btn"
                      className="py-3 px-4 rounded-xl bg-white hover:bg-slate-50 border border-slate-300 text-slate-700 font-bold text-xs flex items-center justify-center gap-2 transition-all shadow-sm active:scale-95"
                    >
                      <Upload className="w-4 h-4 text-slate-500" />
                      <span>Open Device Camera / Photos</span>
                    </button>
                  </div>

                  <input
                    ref={nativeCameraInputRef}
                    type="file"
                    accept="image/*"
                    capture="environment"
                    onChange={handleFileSelect}
                    className="hidden"
                  />
                </div>
              )}

              {/* STEP: CAMERA CAPTURE VIEWFINDER */}
              {step === 'camera' && (
                <div className="flex flex-col h-full space-y-3.5">
                  <div className="flex items-center justify-between bg-slate-100 p-2.5 rounded-xl border border-slate-200 text-xs">
                    <div className="flex items-center gap-2 min-w-0">
                      <Camera className="w-4 h-4 text-[#0F58B6] flex-shrink-0" />
                      <span className="font-bold text-slate-800 truncate">
                        Camera Mode: {facingMode === 'environment' ? 'Back / Document Camera' : 'Front Camera'}
                      </span>
                    </div>
                    <button
                      type="button"
                      onClick={toggleFacingMode}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-slate-300 text-slate-700 font-bold hover:bg-slate-50 transition-all shadow-sm flex-shrink-0 active:scale-95"
                    >
                      <SwitchCamera className="w-3.5 h-3.5 text-[#0F58B6]" />
                      <span>Switch to {facingMode === 'environment' ? 'Front' : 'Back'}</span>
                    </button>
                  </div>

                  {/* Video Viewfinder */}
                  <div className="relative min-h-[300px] sm:min-h-[380px] bg-black rounded-2xl overflow-hidden flex items-center justify-center border-2 border-slate-800 shadow-inner">
                    {cameraError ? (
                      <div className="p-6 text-center space-y-3 text-white max-w-md">
                        <AlertTriangle className="w-8 h-8 text-amber-400 mx-auto" />
                        <p className="text-sm font-bold text-white">Camera Access Notice</p>
                        <p className="text-xs text-slate-300 leading-relaxed">{cameraError}</p>
                        <div className="flex items-center justify-center gap-2 pt-2 flex-wrap">
                          <button
                            type="button"
                            onClick={() => nativeCameraInputRef.current?.click()}
                            className="px-4 py-2 rounded-xl bg-[#0F58B6] hover:bg-[#0c4897] text-white text-xs font-bold"
                          >
                            Open Device Camera
                          </button>
                          <button
                            type="button"
                            onClick={() => {
                              stopCamera();
                              setStep('upload');
                            }}
                            className="px-4 py-2 rounded-xl bg-slate-700 hover:bg-slate-600 text-white text-xs font-bold"
                          >
                            Browse Files
                          </button>
                        </div>
                      </div>
                    ) : (
                      <>
                        <video
                          ref={videoRef}
                          autoPlay
                          playsInline
                          muted
                          className="w-full h-full object-cover"
                        />
                        {/* Viewfinder Target Guidelines */}
                        <div className="absolute inset-4 sm:inset-6 border-2 border-white/50 border-dashed rounded-2xl pointer-events-none flex flex-col justify-between p-3">
                          <span className="text-[10px] font-mono text-white bg-black/60 px-2.5 py-1 rounded-md self-start font-bold">
                            Align prescription / lab report inside frame
                          </span>
                          <div className="w-full text-center">
                            <span className="text-[10px] font-mono text-white bg-black/60 px-2.5 py-1 rounded-md font-bold">
                              Ensure text is well lit and readable
                            </span>
                          </div>
                        </div>
                      </>
                    )}
                  </div>

                  {/* Controls */}
                  <div className="flex items-center justify-between gap-3 pt-1">
                    <button
                      type="button"
                      onClick={() => {
                        stopCamera();
                        setStep('upload');
                      }}
                      className="px-4 py-3 rounded-xl border border-slate-300 text-slate-700 font-bold text-xs hover:bg-slate-50 transition-all"
                    >
                      Cancel
                    </button>

                    {!cameraError && (
                      <button
                        type="button"
                        onClick={capturePhoto}
                        id="capture-doc-photo-btn"
                        className="flex-1 py-3 px-6 rounded-xl bg-[#0F58B6] hover:bg-[#0c4897] text-white font-bold text-xs flex items-center justify-center gap-2 shadow-lg shadow-blue-600/25 transition-all active:scale-95"
                      >
                        <Camera className="w-4 h-4" />
                        <span>Capture Document Photo</span>
                      </button>
                    )}
                  </div>
                </div>
              )}

              {/* STEP: SCANNING & EXTRACTING */}
              {(step === 'scanning' || step === 'extracting') && (
                <OCRScanProgress
                  fileName={selectedFile?.name || 'Medical Document'}
                  previewUrl={previewUrl}
                  progressPercent={scanProgress}
                  statusMessage={statusMessage}
                  isPdf={selectedFile?.type === 'application/pdf'}
                />
              )}

              {/* STEP: CLASSIFIED NOTICE (HOSPITAL RECORD USER ACCEPTANCE OR NON-MEDICAL NOTICE) */}
              {step === 'classified_notice' && (
                <div className="space-y-4">
                  {/* If STRICTLY non-medical, show blocking alert */}
                  {!activeClassification.isHealthcare ? (
                    <div className="p-6 rounded-2xl bg-rose-50 border border-rose-200 text-rose-900 space-y-4">
                      <div className="flex items-start gap-3">
                        <ShieldAlert className="w-8 h-8 text-rose-600 flex-shrink-0" />
                        <div>
                          <h4 className="text-base font-bold text-rose-900">Non-Medical Document Detected</h4>
                          <p className="text-xs text-rose-700 mt-1 leading-relaxed">
                            {activeClassification.verdictSummary ||
                              'The uploaded file is not recognized as an official healthcare or clinical document.'}
                          </p>
                          <p className="text-xs font-medium text-rose-800 mt-2">
                            Prescriptime strictly requires medical documents (prescriptions, diagnostic lab reports, radiology scans, or hospital records).
                          </p>
                        </div>
                      </div>

                      <button
                        type="button"
                        onClick={resetState}
                        className="w-full py-3 rounded-xl bg-rose-700 hover:bg-rose-800 text-white text-xs font-bold transition-all"
                      >
                        Try Another Document
                      </button>
                    </div>
                  ) : (
                    /* Valid Hospital Record: Display User Acceptance Review */
                    <div className="space-y-4">
                      <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-4 shadow-sm">
                        {/* Title and Category */}
                        <div className="flex items-start justify-between flex-wrap gap-2">
                          <div>
                            <div className="flex items-center gap-2 mb-1">
                              <span
                                className={`text-xs px-2.5 py-0.5 rounded-full font-bold border ${getBadgeColorClasses(
                                  activeClassification.badgeColor
                                )}`}
                              >
                                {activeClassification.categoryLabel}
                              </span>
                              <span className="text-[11px] font-mono text-[#0F58B6] font-bold">
                                {Math.round(activeClassification.confidence * 100)}% Confidence
                              </span>
                            </div>
                            <h3 className="text-base font-bold text-slate-900">
                              {extractedData?.diagnosis_or_test ||
                                activeClassification.detectedEntities?.diagnosisOrTest ||
                                activeClassification.categoryLabel}
                            </h3>
                          </div>
                        </div>

                        {/* Extracted Metadata Grid */}
                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
                          <div className="p-3 rounded-xl bg-white border border-slate-200 space-y-0.5">
                            <span className="text-[10px] font-mono text-slate-400 uppercase font-bold flex items-center gap-1">
                              <Hospital className="w-3 h-3 text-blue-600" />
                              <span>Facility</span>
                            </span>
                            <span className="font-bold text-slate-800 truncate block">
                              {extractedData?.clinic_or_hospital ||
                                activeClassification.detectedEntities?.clinicOrHospital ||
                                'Hospital Center'}
                            </span>
                          </div>

                          <div className="p-3 rounded-xl bg-white border border-slate-200 space-y-0.5">
                            <span className="text-[10px] font-mono text-slate-400 uppercase font-bold flex items-center gap-1">
                              <User className="w-3 h-3 text-blue-600" />
                              <span>Doctor / Specialist</span>
                            </span>
                            <span className="font-bold text-slate-800 truncate block">
                              {extractedData?.doctor_name ||
                                activeClassification.detectedEntities?.doctorName ||
                                'Clinical Specialist'}
                            </span>
                          </div>

                          <div className="p-3 rounded-xl bg-white border border-slate-200 space-y-0.5">
                            <span className="text-[10px] font-mono text-slate-400 uppercase font-bold flex items-center gap-1">
                              <Calendar className="w-3 h-3 text-blue-600" />
                              <span>Document Date</span>
                            </span>
                            <span className="font-bold text-slate-800 block">
                              {extractedData?.date ||
                                activeClassification.detectedEntities?.date ||
                                new Date().toISOString().split('T')[0]}
                            </span>
                          </div>
                        </div>

                        {/* Clinical Summary */}
                        <div className="p-3.5 rounded-xl bg-white border border-slate-200 space-y-1">
                          <span className="text-[10px] font-mono text-slate-400 uppercase font-bold">
                            Clinical Impression / Findings:
                          </span>
                          <p className="text-xs text-slate-700 leading-relaxed font-medium">
                            {extractedData?.notes || activeClassification.verdictSummary}
                          </p>
                        </div>

                        {/* Key Indicators Identified */}
                        {activeClassification.keyIndicators?.length > 0 && (
                          <div className="p-3 rounded-xl bg-white border border-slate-200 space-y-1.5">
                            <span className="text-[10px] font-mono text-slate-400 uppercase font-bold">
                              Verified Clinical Indicators:
                            </span>
                            <div className="flex flex-wrap gap-1.5">
                              {activeClassification.keyIndicators.map((ind, i) => (
                                <span
                                  key={i}
                                  className="text-[11px] px-2.5 py-0.5 rounded-lg bg-slate-50 border border-slate-200 text-slate-700 font-medium"
                                >
                                  ✓ {ind}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Family Member Attribution */}
                        <div className="p-3.5 rounded-xl bg-white border border-slate-200 shadow-sm">
                          <FamilyMemberSelector
                            selectedRelation={hrFamilyMember}
                            onSelectRelation={setHrFamilyMember}
                            patientName={hrPatientName}
                            onPatientNameChange={setHrPatientName}
                            customRelation={hrCustomRelation}
                            onCustomRelationChange={setHrCustomRelation}
                          />
                        </div>
                      </div>

                      {/* User Acceptance Buttons */}
                      <div className="flex flex-col sm:flex-row items-center gap-2.5 pt-2">
                        <button
                          type="button"
                          onClick={resetState}
                          className="w-full sm:w-auto px-4 py-3 rounded-xl border border-slate-200 text-slate-600 text-xs font-bold hover:bg-slate-50 transition-all"
                        >
                          Cancel / Re-upload
                        </button>

                        <button
                          type="button"
                          onClick={handleAcceptHospitalRecord}
                          id="accept-hospital-record-btn"
                          className="w-full sm:flex-1 py-3 px-5 rounded-xl bg-[#0F58B6] hover:bg-[#0c4897] text-white text-xs font-bold flex items-center justify-center gap-2 transition-all shadow-md shadow-blue-600/20 active:scale-95"
                        >
                          <Check className="w-4 h-4" />
                          <span>Accept &amp; Save to Health Records</span>
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* STEP: SUCCESS */}
              {step === 'success' && (
                <div className="flex flex-col items-center justify-center py-12 space-y-4 text-center">
                  <div className="w-16 h-16 rounded-full bg-emerald-100 border border-emerald-300 text-emerald-600 flex items-center justify-center shadow-sm">
                    <CheckCircle2 className="w-9 h-9" />
                  </div>
                  <h3 className="text-lg font-bold text-slate-900">{successMessage}</h3>
                  <p className="text-xs text-slate-600 max-w-sm">
                    Saved to your secure Prescriptime cloud records and accessible across all your devices.
                  </p>
                </div>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
};
