export type MedicationFrequency = 
  | 'OD' // Once daily
  | 'BD' // Twice daily
  | 'TDS' // Three times daily
  | 'QDS' // Four times daily
  | 'HS' // Bedtime
  | 'PRN' // As needed
  | string;

export type TimeOfDaySlot = 'morning' | 'afternoon' | 'evening' | 'bedtime' | 'as_needed';

export interface Medication {
  id: string;
  name: string;
  genericName?: string;
  dosage: string; // e.g. "500 mg", "1 tablet"
  frequency: string; // e.g. "BD", "Twice daily", "1-0-1"
  route?: string; // Oral, Topical, etc.
  timing?: 'before_food' | 'after_food' | 'with_food' | 'anytime' | string;
  specific_time?: string;
  flagged_for_review?: boolean;
  duration?: string; // e.g. "5 days", "1 month"
  instructions?: string;
  remainingPills?: number;
  totalPrescribedPills?: number;
  refillThreshold?: number;
}

export type DocumentClassificationType =
  | 'prescription'
  | 'lab_report'
  | 'radiology_scan'
  | 'discharge_summary'
  | 'medical_invoice'
  | 'other_medical'
  | 'non_medical';

export interface DocumentClassification {
  documentType: DocumentClassificationType;
  categoryLabel: string;
  isHealthcare: boolean;
  isPrescription: boolean;
  confidence: number;
  badgeColor: 'emerald' | 'amber' | 'cyan' | 'purple' | 'orange' | 'rose';
  verdictSummary: string;
  keyIndicators: string[];
  guidance: string;
  detectedEntities?: {
    doctorName?: string;
    clinicOrHospital?: string;
    patientName?: string;
    date?: string;
    diagnosisOrTest?: string;
    medicationCount: number;
  };
}

export interface ExtractedData {
  document_type: 'prescription' | 'diagnostic_report' | 'discharge_summary' | 'lab_report' | 'radiology_scan' | 'other';
  is_valid_medical_document?: boolean;
  is_healthcare_document?: boolean;
  is_prescription?: boolean;
  invalid_reason?: string;
  detected_document_type?: string;
  classification?: DocumentClassification;
  doctor_name?: string;
  clinic_or_hospital?: string;
  patient_name?: string;
  date?: string; // ISO format: YYYY-MM-DD
  diagnosis?: string;
  diagnosis_or_test?: string;
  medications: Medication[];
  follow_up_date?: string;
  notes?: string;
  raw_text?: string;
  family_member?: FamilyMemberRelation;
  patient_relation?: string;
}

export type FamilyMemberRelation =
  | 'self'
  | 'father'
  | 'mother'
  | 'spouse'
  | 'son'
  | 'daughter'
  | 'brother'
  | 'sister'
  | 'grandfather'
  | 'grandmother'
  | 'other';

export interface DoctorVisitVitals {
  bloodPressure?: string;
  pulse?: string;
  weight?: string;
  temperature?: string;
}

export interface DoctorVisit {
  id: string;
  prescriptionId: string;
  visitDate: string; // YYYY-MM-DD
  doctorName: string;
  clinicOrHospital?: string;
  reasonForVisit?: string;
  diagnosis?: string;
  vitals?: DoctorVisitVitals;
  clinicalNotes?: string;
  treatmentPlan?: string;
  nextFollowUpDate?: string;
  isAutoGenerated?: boolean;
  createdAt: string;
}

export interface Prescription {
  id: string;
  userId?: string;
  title: string;
  doctorName?: string;
  clinicOrHospital?: string;
  patientName?: string;
  familyMember?: FamilyMemberRelation;
  patientRelation?: string;
  date: string;
  uploadedAt?: string;
  diagnosis?: string;
  medications: Medication[];
  notes?: string;
  followUpDate?: string;
  rawText?: string;
  fileUrl?: string;
  fileName?: string;
  fileType?: 'image' | 'pdf';
  fileSize?: number;
  createdAt: string;
  status: 'active' | 'completed' | 'archived';
  doctorVisits?: DoctorVisit[];
  explanations?: Record<string, string>;
}

export type ExplainerLanguage = 'en' | 'te' | 'hi' | 'ta';

export type HealthRecordDocumentType =
  | 'lab_report'
  | 'radiology_scan'
  | 'discharge_summary'
  | 'consultation_note'
  | 'other_medical';

export interface HealthRecord {
  id: string;
  userId?: string;
  title: string;
  documentType: HealthRecordDocumentType;
  categoryLabel: string;
  doctorName?: string;
  clinicOrHospital?: string;
  patientName?: string;
  familyMember?: FamilyMemberRelation;
  patientRelation?: string;
  date: string;
  uploadedAt: string;
  diagnosisOrTest?: string;
  summary?: string;
  keyIndicators?: string[];
  testResults?: Array<{
    parameter: string;
    value: string;
    unit?: string;
    referenceRange?: string;
    flag?: 'normal' | 'high' | 'low' | 'abnormal';
  }>;
  notes?: string;
  rawText?: string;
  fileUrl?: string;
  fileName: string;
  fileType: 'image' | 'pdf';
  fileSize?: number;
  createdAt: string;
  status: 'active' | 'archived';
  doctorVisits?: DoctorVisit[];
}

export interface ScheduledDose {
  id: string;
  userId?: string;
  prescriptionId: string;
  medicationId: string;
  medicationName: string;
  dosage: string;
  slot: TimeOfDaySlot;
  scheduledTime: string; // e.g. "08:00 AM"
  timingNotes?: string;
  instructions?: string;
  status: 'pending' | 'taken' | 'skipped' | 'snoozed';
  takenAt?: string;
  date: string; // YYYY-MM-DD
  reminderEnabled?: boolean;
  repeatDays?: string[]; // e.g. ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']
  familyMember?: FamilyMemberRelation;
  patientName?: string;
}

export interface AdherenceDayRecord {
  date: string; // YYYY-MM-DD
  totalScheduled: number;
  totalTaken: number;
  totalSkipped?: number;
  adherencePercentage: number;
}

