'use client';

import React, { useState, useMemo, useEffect, useRef } from 'react';
import { Prescription, DoctorVisit } from '@/types/prescription';
import {
  X,
  Calendar,
  User,
  Hospital,
  Activity,
  Pill,
  FileText,
  Printer,
  Eye,
  Download,
  Loader2,
  Users,
  Edit3,
  Upload,
  Stethoscope,
  Plus,
  Trash2,
  Heart,
  Thermometer,
  Clock,
  CheckCircle2,
  AlertCircle,
  Sparkles,
  Volume2,
  VolumeX,
  Square,
  Play,
  Copy,
  Check,
} from 'lucide-react';
import { useBodyScrollLock } from '@/lib/useBodyScrollLock';
import { deduplicateMedications } from '@/lib/deduplication';
import { getFamilyRelationBadge } from '@/lib/familyMembers';
import { getStoredFile, saveStoredFile } from '@/lib/fileStorage';
import {
  savePrescription,
  getActiveUserId,
  authFetch,
  addDoctorVisitToPrescription,
  deleteDoctorVisitFromPrescription,
  autoGenerateDoctorVisitForPrescription,
} from '@/lib/storage';
import {
  generateExplanation,
  speakWithFallback,
  stopSpeech,
  isSpeaking,
  primeAudioPlayback,
} from '@/lib/voiceExplainer';
import { ExplainerLanguage } from '@/types/prescription';

interface PrescriptionDetailsModalProps {
  prescription: Prescription | null;
  onClose: () => void;
  onEdit?: (prescription: Prescription) => void;
  onUpdate?: (updated: Prescription) => void;
}

export const PrescriptionDetailsModal: React.FC<PrescriptionDetailsModalProps> = ({
  prescription,
  onClose,
  onEdit,
  onUpdate,
}) => {
  useBodyScrollLock(!!prescription);
  const [activeRx, setActiveRx] = useState<Prescription | null>(prescription);
  const [activeView, setActiveView] = useState<'original' | 'digital' | 'visits' | 'explain'>('digital');
  const [resolvedFileUrl, setResolvedFileUrl] = useState<string | undefined>(
    prescription?.fileUrl && prescription.fileUrl !== '[offline-cached-scan]' ? prescription.fileUrl : undefined
  );
  const [loadingScan, setLoadingScan] = useState(false);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  // Voice Explainer State
  const [explainerLang, setExplainerLang] = useState<ExplainerLanguage>('en');
  const [explanationText, setExplanationText] = useState<string>('');
  const [isGeneratingExplanation, setIsGeneratingExplanation] = useState(false);
  const [isSpeakingAudio, setIsSpeakingAudio] = useState(false);
  const [fallbackToast, setFallbackToast] = useState<string | null>(null);
  const [copiedExplanation, setCopiedExplanation] = useState(false);

  // Stop any ongoing speech on modal unmount
  useEffect(() => {
    return () => {
      stopSpeech();
    };
  }, []);

  // Sync cached explanation when prescription or language changes
  useEffect(() => {
    const rx = activeRx || prescription;
    if (rx?.explanations && rx.explanations[explainerLang]) {
      setExplanationText(rx.explanations[explainerLang]);
    } else {
      setExplanationText('');
    }
  }, [prescription, activeRx, explainerLang]);

  const handleModalClose = () => {
    stopSpeech();
    setIsSpeakingAudio(false);
    onClose();
  };

  const handleSelectLanguage = (lang: ExplainerLanguage) => {
    if (lang === explainerLang) return;
    stopSpeech();
    setIsSpeakingAudio(false);
    setExplainerLang(lang);
  };

  const handleToggleSpeech = async () => {
    const currentPrescription = activeRx || prescription;
    if (!currentPrescription) return;

    if (isSpeakingAudio) {
      stopSpeech();
      setIsSpeakingAudio(false);
      return;
    }

    // Unlock browser audio context synchronously on user click
    primeAudioPlayback();

    let textToSpeak = explanationText;

    // Step 1: Generate plain-language explanation via Gemini if not yet cached
    if (!textToSpeak || textToSpeak.trim().length === 0) {
      try {
        setIsGeneratingExplanation(true);
        textToSpeak = await generateExplanation(currentPrescription, explainerLang);
        setExplanationText(textToSpeak);

        const updatedRx: Prescription = {
          ...currentPrescription,
          explanations: {
            ...(currentPrescription.explanations || {}),
            [explainerLang]: textToSpeak,
          },
        };
        setActiveRx(updatedRx);
        if (onUpdate) {
          onUpdate(updatedRx);
        }
      } catch (err: any) {
        setFallbackToast(err?.message || 'Failed to generate explanation.');
        setTimeout(() => setFallbackToast(null), 5000);
        return;
      } finally {
        setIsGeneratingExplanation(false);
      }
    }

    // Step 2: Stream audio via Sarvam AI TTS proxy, falling back gracefully to Web Speech
    try {
      setIsSpeakingAudio(true);
      await speakWithFallback(textToSpeak, explainerLang, {
        onStart: () => setIsSpeakingAudio(true),
        onEnd: () => setIsSpeakingAudio(false),
        onError: () => {
          setIsSpeakingAudio(false);
        },
        onFallback: () => {
          setFallbackToast('Using browser speech synthesis fallback (Sarvam AI unavailable).');
          setTimeout(() => setFallbackToast(null), 6000);
        },
      });
    } catch {
      setIsSpeakingAudio(false);
    }
  };

  const handleCopyExplanation = () => {
    if (!explanationText) return;
    navigator.clipboard.writeText(explanationText);
    setCopiedExplanation(true);
    setTimeout(() => setCopiedExplanation(false), 2000);
  };

  useEffect(() => {
    setActiveRx(prescription);
  }, [prescription]);

  // Doctor Visit Form State
  const [isAddingVisit, setIsAddingVisit] = useState(false);
  const [visitDate, setVisitDate] = useState(() => new Date().toISOString().split('T')[0]);
  const [visitDoctor, setVisitDoctor] = useState('');
  const [visitClinic, setVisitClinic] = useState('');
  const [visitReason, setVisitReason] = useState('');
  const [visitDiagnosis, setVisitDiagnosis] = useState('');
  const [visitBp, setVisitBp] = useState('');
  const [visitPulse, setVisitPulse] = useState('');
  const [visitWeight, setVisitWeight] = useState('');
  const [visitTemp, setVisitTemp] = useState('');
  const [visitNotes, setVisitNotes] = useState('');
  const [visitFollowUp, setVisitFollowUp] = useState('');

  useEffect(() => {
    if (!prescription) return;

    let isMounted = true;
    let safetyTimeout: NodeJS.Timeout | null = setTimeout(() => {
      if (isMounted) {
        setLoadingScan(false);
      }
    }, 2500);

    if (prescription.fileUrl && prescription.fileUrl !== '[offline-cached-scan]') {
      setResolvedFileUrl(prescription.fileUrl);
      setLoadingScan(false);
      if (safetyTimeout) clearTimeout(safetyTimeout);
      return;
    }

    setLoadingScan(true);

    // Check IndexedDB first for instant offline scan rendering
    getStoredFile(prescription.id)
      .then((storedScan) => {
        if (!isMounted) return;
        if (storedScan) {
          setResolvedFileUrl(storedScan);
          setLoadingScan(false);
          if (safetyTimeout) clearTimeout(safetyTimeout);
          return;
        }

        // Fallback: Fetch from server API with authenticated user ID
        const uid = getActiveUserId() || prescription.userId;
        const userParam = uid ? `&userId=${encodeURIComponent(uid)}` : '';
        authFetch(`/api/prescriptions?id=${encodeURIComponent(prescription.id)}&includeFiles=true${userParam}`, {
          signal: AbortSignal.timeout(2500),
        }, uid || undefined)
          .then((r) => r.json())
          .then((res) => {
            if (!isMounted) return;
            if (res.success && res.data?.[0]?.fileUrl) {
              const serverUrl = res.data[0].fileUrl;
              setResolvedFileUrl(serverUrl);
              saveStoredFile(prescription.id, serverUrl).catch(() => {});
            }
          })
          .catch(() => {})
          .finally(() => {
            if (isMounted) setLoadingScan(false);
            if (safetyTimeout) clearTimeout(safetyTimeout);
          });
      })
      .catch(() => {
        if (isMounted) setLoadingScan(false);
        if (safetyTimeout) clearTimeout(safetyTimeout);
      });

    return () => {
      isMounted = false;
      if (safetyTimeout) clearTimeout(safetyTimeout);
    };
  }, [prescription?.id, prescription?.fileUrl, prescription?.userId]);

  const handleAttachScan = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !prescription) return;
    const isPdf = file.type === 'application/pdf';
    const reader = new FileReader();
    reader.onload = async (event) => {
      const dataUrl = event.target?.result as string;
      if (dataUrl) {
        setResolvedFileUrl(dataUrl);
        await saveStoredFile(prescription.id, dataUrl);
        const updated: Prescription = {
          ...prescription,
          fileUrl: dataUrl,
          fileName: file.name,
          fileType: isPdf ? 'pdf' : 'image',
        };
        savePrescription(updated);
        if (onUpdate) onUpdate(updated);
      }
    };
    reader.readAsDataURL(file);
  };

  const uniqueMedications = useMemo(
    () => deduplicateMedications(prescription?.medications || []),
    [prescription?.medications]
  );

  if (!prescription) return null;

  const activeScanUrl = resolvedFileUrl || (prescription.fileUrl && prescription.fileUrl !== '[offline-cached-scan]' ? prescription.fileUrl : undefined);

  const handlePrintOriginal = () => {
    if (!activeScanUrl) {
      window.print();
      return;
    }

    try {
      const existingIframe = document.getElementById('prescriptime-print-iframe');
      if (existingIframe) {
        existingIframe.remove();
      }

      const iframe = document.createElement('iframe');
      iframe.id = 'prescriptime-print-iframe';
      iframe.style.position = 'fixed';
      iframe.style.right = '0';
      iframe.style.bottom = '0';
      iframe.style.width = '0';
      iframe.style.height = '0';
      iframe.style.border = '0';
      document.body.appendChild(iframe);

      const isPdf = prescription.fileType === 'pdf' || activeScanUrl.startsWith('data:application/pdf');

      if (isPdf) {
        iframe.src = activeScanUrl;
        iframe.onload = () => {
          setTimeout(() => {
            iframe.contentWindow?.focus();
            iframe.contentWindow?.print();
          }, 400);
        };
      } else {
        const doc = iframe.contentWindow?.document;
        if (doc) {
          doc.open();
          doc.write(`
            <!DOCTYPE html>
            <html>
              <head>
                <title>Print ${prescription.fileName || 'Prescription Scan'}</title>
                <style>
                  @page { size: auto; margin: 10mm; }
                  body { margin: 0; padding: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; background: #fff; }
                  img { max-width: 100%; max-height: 100vh; object-fit: contain; }
                </style>
              </head>
              <body>
                <img id="print-scan-img" src="${activeScanUrl}" alt="Prescription Scan" />
                <script>
                  const img = document.getElementById('print-scan-img');
                  if (img && img.complete) {
                    setTimeout(() => window.print(), 250);
                  } else if (img) {
                    img.onload = () => setTimeout(() => window.print(), 250);
                  }
                </script>
              </body>
            </html>
          `);
          doc.close();
        }
      }
    } catch {
      window.print();
    }
  };

  const formattedUploadDate = prescription.uploadedAt
    ? new Date(prescription.uploadedAt).toLocaleDateString('en-IN', {
        timeZone: 'Asia/Kolkata',
        month: 'short',
        day: 'numeric',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
    : (prescription.createdAt ? new Date(prescription.createdAt).toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata' }) : 'Recently');

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-900/65 backdrop-blur-sm animate-in fade-in duration-200 overflow-y-auto overscroll-contain"
      data-lenis-prevent="true"
    >
      <div
        id="prescription-details-modal"
        className="relative w-full max-w-4xl max-h-[92vh] flex flex-col rounded-3xl bg-white border border-slate-200 shadow-2xl overflow-hidden text-slate-900 my-auto"
        data-lenis-prevent="true"
      >
        {/* Close Button */}
        <button
          onClick={handleModalClose}
          id="close-prescription-modal-btn"
          className="absolute top-4 right-4 sm:top-5 sm:right-5 p-2 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors z-20"
          aria-label="Close modal"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Modal Header */}
        <div className="p-5 sm:p-6 pb-4 border-b border-slate-200 flex-shrink-0 pr-16 bg-slate-50/50">
          <div className="flex flex-wrap items-center gap-2 mb-1.5">
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-50 text-[#0F58B6] border border-blue-200 font-mono font-bold">
              Digital Cabinet Record
            </span>
            {(() => {
              const badge = getFamilyRelationBadge(prescription.familyMember || 'self');
              const label = prescription.familyMember === 'other' && prescription.patientRelation ? prescription.patientRelation : badge.label;
              return (
                <span className={`text-xs px-2.5 py-0.5 rounded-full border font-semibold flex items-center gap-1 ${badge.badgeBg}`}>
                  <span>{badge.icon}</span>
                  <span>{label}</span>
                  {prescription.patientName && <span className="font-normal">({prescription.patientName})</span>}
                </span>
              );
            })()}
            <span className="text-xs font-mono text-slate-500 font-semibold">
              ID: {prescription.id}
            </span>
            <span className="text-[11px] font-mono text-slate-500 font-semibold">
              • Uploaded: {formattedUploadDate}
            </span>
          </div>
          <h2 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight">{prescription.title}</h2>

          {/* Dual-View Switcher Tab Bar */}
          <div className="flex flex-wrap items-center gap-2 mt-3 pt-2">
            <button
              type="button"
              id="tab-digital-prescription"
              onClick={() => {
                stopSpeech();
                setIsSpeakingAudio(false);
                setActiveView('digital');
              }}
              className={`flex items-center gap-1.5 px-3 sm:px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                activeView === 'digital'
                  ? 'bg-[#0F58B6] text-white shadow-sm shadow-blue-500/20'
                  : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-100'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Digital Prescription</span>
            </button>

            <button
              type="button"
              id="tab-voice-explainer"
              onClick={() => {
                stopSpeech();
                setIsSpeakingAudio(false);
                setActiveView('explain');
              }}
              className={`flex items-center gap-1.5 px-3 sm:px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                activeView === 'explain'
                  ? 'bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-sm shadow-blue-500/25'
                  : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-100'
              }`}
            >
              <Volume2 className={`w-3.5 h-3.5 ${activeView === 'explain' ? 'text-white' : 'text-blue-600'}`} />
              <span>Voice Explainer</span>
              <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-bold ${
                activeView === 'explain' ? 'bg-white/20 text-white' : 'bg-blue-50 text-blue-700 border border-blue-200'
              }`}>
                Sarvam AI
              </span>
            </button>

            <button
              type="button"
              id="tab-doctor-visits"
              onClick={() => {
                stopSpeech();
                setIsSpeakingAudio(false);
                setActiveView('visits');
              }}
              className={`flex items-center gap-1.5 px-3 sm:px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                activeView === 'visits'
                  ? 'bg-[#0F58B6] text-white shadow-sm shadow-blue-500/20'
                  : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-100'
              }`}
            >
              <Stethoscope className="w-3.5 h-3.5" />
              <span>Doctor Visits ({activeRx?.doctorVisits?.length ?? prescription?.doctorVisits?.length ?? 0})</span>
            </button>

            <button
              type="button"
              id="tab-original-scan"
              onClick={() => {
                stopSpeech();
                setIsSpeakingAudio(false);
                setActiveView('original');
              }}
              className={`flex items-center gap-1.5 px-3 sm:px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                activeView === 'original'
                  ? 'bg-[#0F58B6] text-white shadow-sm shadow-blue-500/20'
                  : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-100'
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>Original Scan</span>
            </button>

            {/* Hidden Scan File Input for Uploading/Replacing */}
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*,application/pdf"
              onChange={handleAttachScan}
              className="hidden"
              id="prescription-scan-upload-input"
            />

            <div className="sm:ml-auto flex items-center gap-2">
              {onEdit && (
                <button
                  type="button"
                  onClick={() => onEdit(prescription)}
                  id="modal-edit-prescription-btn"
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-blue-50 border border-blue-200 hover:bg-blue-100 text-[#0F58B6] text-xs font-bold transition-all shadow-sm cursor-pointer"
                  title="Edit Prescription Details"
                >
                  <Edit3 className="w-3.5 h-3.5" />
                  <span>Edit</span>
                </button>
              )}

              {/* Print Action for current view */}
              <button
                type="button"
                onClick={activeView === 'original' ? handlePrintOriginal : () => window.print()}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white border border-slate-200 hover:bg-slate-100 text-slate-700 text-xs font-bold transition-all shadow-sm"
                title="Print Document"
              >
                <Printer className="w-3.5 h-3.5 text-blue-600" />
                <span>Print {activeView === 'original' ? 'Original' : 'Summary'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* Scrollable Content */}
        <div
          className="p-5 sm:p-7 overflow-y-auto overscroll-contain flex-1 min-h-0 space-y-6"
          data-lenis-prevent="true"
          style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}
        >
          {/* TAB 1: ORIGINAL UPLOADED DOCUMENT VIEW */}
          {activeView === 'original' && (
            <div className="space-y-4">
              {loadingScan ? (
                <div className="rounded-2xl border border-slate-200 overflow-hidden bg-slate-900/5 p-12 flex flex-col items-center justify-center min-h-[360px] gap-3">
                  <Loader2 className="w-8 h-8 text-[#0F58B6] animate-spin" />
                  <p className="text-xs font-semibold text-slate-600">Loading prescription scan...</p>
                </div>
              ) : activeScanUrl ? (
                <div className="rounded-2xl border border-slate-200 overflow-hidden bg-slate-900/5 p-2 flex flex-col items-center justify-center min-h-[360px]">
                  {prescription.fileType === 'pdf' || activeScanUrl.startsWith('data:application/pdf') ? (
                    <iframe
                      src={activeScanUrl}
                      title={prescription.fileName || 'Original Prescription'}
                      className="w-full h-[550px] rounded-xl border border-slate-200 bg-white shadow-inner"
                    />
                  ) : (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={activeScanUrl}
                      alt={prescription.fileName || 'Prescription Scan'}
                      className="max-h-[600px] w-auto object-contain rounded-xl shadow-md border border-white"
                    />
                  )}
                  <div className="mt-3 flex items-center justify-between w-full px-2 text-xs font-mono text-slate-500 flex-wrap gap-2">
                    <span className="truncate max-w-xs">{prescription.fileName || 'Original Document'}</span>
                    <div className="flex items-center gap-3">
                      <button
                        type="button"
                        onClick={() => fileInputRef.current?.click()}
                        className="text-slate-600 font-bold hover:text-[#0F58B6] hover:underline inline-flex items-center gap-1 cursor-pointer"
                        id="replace-scan-btn"
                      >
                        <Upload className="w-3.5 h-3.5" />
                        <span>Replace Scan</span>
                      </button>
                      <button
                        type="button"
                        onClick={handlePrintOriginal}
                        className="text-[#0F58B6] font-bold hover:underline inline-flex items-center gap-1 cursor-pointer"
                      >
                        <Printer className="w-3.5 h-3.5" />
                        <span>Print Original Scan</span>
                      </button>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="p-8 text-center rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
                  <FileText className="w-10 h-10 text-slate-300 mx-auto" />
                  <div>
                    <p className="text-sm font-semibold text-slate-700">Digital Record Stored</p>
                    <p className="text-xs text-slate-500 mt-0.5">
                      The verified extracted medicines are ready in the Digital Prescription tab.
                    </p>
                  </div>
                  <div className="pt-2">
                    <button
                      type="button"
                      onClick={() => fileInputRef.current?.click()}
                      id="attach-original-scan-btn"
                      className="px-4 py-2 rounded-xl bg-[#0F58B6] hover:bg-[#0c4897] text-white text-xs font-bold shadow-md shadow-blue-500/20 inline-flex items-center gap-1.5 cursor-pointer transition-all active:scale-95"
                    >
                      <Upload className="w-4 h-4" />
                      <span>Attach Original File / Scan</span>
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 2: DIGITAL STRUCTURED VIEW */}
          {activeView === 'digital' && (
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
              {/* Left Column: Metadata & Notes */}
              <div className="lg:col-span-5 space-y-4">
                {/* Voice Explainer Callout Card */}
                <div className="p-4 rounded-2xl bg-gradient-to-br from-blue-50/90 via-indigo-50/50 to-white border border-blue-200 shadow-sm flex items-center justify-between gap-3">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center flex-shrink-0 shadow-md shadow-blue-500/20">
                      <Volume2 className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-slate-900">Voice Explainer (AI)</h4>
                      <p className="text-[11px] text-slate-600 leading-tight mt-0.5">
                        Listen to plain words in EN, Telugu, Hindi, or Tamil.
                      </p>
                    </div>
                  </div>
                  <button
                    type="button"
                    id="digital-tab-explain-btn"
                    onClick={() => {
                      stopSpeech();
                      setIsSpeakingAudio(false);
                      setActiveView('explain');
                    }}
                    className="px-3 py-1.5 rounded-xl bg-white border border-blue-200 hover:bg-blue-50 text-blue-700 text-xs font-bold transition-all shadow-sm flex-shrink-0 cursor-pointer active:scale-95"
                  >
                    Explain to Me
                  </button>
                </div>

                <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
                  <div className="flex items-center gap-2.5 text-xs text-slate-700">
                    <Users className="w-4 h-4 text-indigo-600" />
                    <div>
                      <p className="text-[10px] font-mono text-slate-500 uppercase font-bold">Family Attribution</p>
                      <div className="flex items-center gap-2 mt-0.5">
                        {(() => {
                          const badge = getFamilyRelationBadge(prescription.familyMember || 'self');
                          const label = prescription.familyMember === 'other' && prescription.patientRelation ? prescription.patientRelation : badge.label;
                          return (
                            <span className={`text-xs px-2.5 py-0.5 rounded-full border font-semibold flex items-center gap-1 ${badge.badgeBg}`}>
                              <span>{badge.icon}</span>
                              <span>{label}</span>
                            </span>
                          );
                        })()}
                        {prescription.patientName && (
                          <span className="text-xs font-bold text-slate-800">
                            • Patient: {prescription.patientName}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-2.5 text-xs text-slate-700">
                    <User className="w-4 h-4 text-[#0F58B6]" />
                    <div>
                      <p className="text-[10px] font-mono text-slate-500 uppercase font-bold">Prescribing Doctor</p>
                      <p className="font-bold text-slate-900">{prescription.doctorName || 'Not Stated'}</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2.5 text-xs text-slate-700">
                    <Hospital className="w-4 h-4 text-[#0F58B6]" />
                    <div>
                      <p className="text-[10px] font-mono text-slate-500 uppercase font-bold">Facility</p>
                      <p className="font-bold text-slate-900">{prescription.clinicOrHospital || 'Clinic'}</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2.5 text-xs text-slate-700">
                    <Calendar className="w-4 h-4 text-[#0F58B6]" />
                    <div>
                      <p className="text-[10px] font-mono text-slate-500 uppercase font-bold">Date Prescribed</p>
                      <p className="font-bold text-slate-900">{prescription.date}</p>
                    </div>
                  </div>

                  {prescription.followUpDate && (
                    <div className="flex items-center gap-2.5 text-xs text-slate-700">
                      <Calendar className="w-4 h-4 text-emerald-600" />
                      <div>
                        <p className="text-[10px] font-mono text-emerald-600 uppercase font-bold">Follow-Up Date</p>
                        <p className="font-bold text-slate-900">{prescription.followUpDate}</p>
                      </div>
                    </div>
                  )}

                  <div className="flex items-center gap-2.5 text-xs text-slate-700">
                    <Activity className="w-4 h-4 text-[#0F58B6]" />
                    <div>
                      <p className="text-[10px] font-mono text-slate-500 uppercase font-bold">Clinical Diagnosis</p>
                      <p className="font-bold text-slate-900">{prescription.diagnosis || 'Clinical Consultation'}</p>
                    </div>
                  </div>
                </div>

                {/* Doctor Directives */}
                {prescription.notes && (
                  <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-1.5">
                    <p className="text-[10px] font-mono text-slate-500 uppercase font-bold">Doctor Directives &amp; Advice</p>
                    <p className="text-xs text-slate-700 leading-relaxed font-medium">{prescription.notes}</p>
                  </div>
                )}
              </div>

              {/* Right Column: Prescribed Medications List */}
              <div className="lg:col-span-7 space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                    <Pill className="w-4 h-4 text-[#0F58B6]" />
                    <span>Prescribed Medications ({uniqueMedications.length})</span>
                  </h3>
                </div>

                <div className="space-y-3">
                  {uniqueMedications.map((med, idx) => (
                    <div
                      key={med.id || idx}
                      className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-2 shadow-sm"
                    >
                      <div className="flex items-center justify-between">
                        <h4 className="text-sm font-bold text-slate-900 tracking-tight">{med.name}</h4>
                        <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-50 text-[#0F58B6] border border-blue-200 font-mono font-bold">
                          {med.dosage}
                        </span>
                      </div>

                      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-xs font-mono text-slate-600 font-medium">
                        <div>
                          <span className="text-[10px] text-slate-400 uppercase block font-bold">Routine:</span>
                          <span className="text-slate-800">{med.frequency}</span>
                        </div>
                        <div>
                          <span className="text-[10px] text-slate-400 uppercase block font-bold">Food Timing:</span>
                          <span className="text-slate-800 capitalize">{med.timing?.replace('_', ' ') || 'After food'}</span>
                        </div>
                        <div>
                          <span className="text-[10px] text-slate-400 uppercase block font-bold">Duration:</span>
                          <span className="text-slate-800">{med.duration || 'As directed'}</span>
                        </div>
                      </div>

                      {med.instructions && (
                        <p className="text-[11px] text-slate-600 pt-1 border-t border-slate-200">
                          <span className="font-bold text-slate-800">Note: </span>
                          {med.instructions}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: DOCTOR-VISIT HISTORY LOG */}
          {activeView === 'visits' && (
            <div className="space-y-6">
              {/* Header & Add Visit Action */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-4 rounded-2xl bg-slate-50 border border-slate-200">
                <div>
                  <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                    <Stethoscope className="w-4 h-4 text-[#0F58B6]" />
                    <span>Doctor Consultation History</span>
                  </h3>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Log and track all doctor visits, vitals, clinical advice, and follow-ups tied to this prescription.
                  </p>
                </div>
                <div className="flex items-center gap-2 flex-wrap">
                  <button
                    type="button"
                    id="btn-auto-extract-visit"
                    onClick={() => {
                      const cur = activeRx || prescription;
                      if (cur) {
                        const updated = autoGenerateDoctorVisitForPrescription(cur.id);
                        if (updated) {
                          setActiveRx(updated);
                          if (onUpdate) onUpdate(updated);
                        }
                      }
                    }}
                    className="flex items-center justify-center gap-1.5 px-3.5 py-2 rounded-xl bg-purple-50 hover:bg-purple-100 text-purple-700 border border-purple-200 text-xs font-bold transition-all active:scale-95 cursor-pointer whitespace-nowrap shadow-sm"
                    title="Automatically extract initial consultation visit from prescription letterhead and details"
                  >
                    <Sparkles className="w-4 h-4 text-purple-600" />
                    <span>Auto-Extract from Rx</span>
                  </button>

                  {!isAddingVisit && (
                    <button
                      type="button"
                      id="btn-log-doctor-visit"
                      onClick={() => {
                        const cur = activeRx || prescription;
                        setVisitDoctor(cur?.doctorName || '');
                        setVisitClinic(cur?.clinicOrHospital || '');
                        setVisitDate(new Date().toISOString().split('T')[0]);
                        setVisitDiagnosis(cur?.diagnosis || '');
                        setIsAddingVisit(true);
                      }}
                      className="flex items-center justify-center gap-1.5 px-4 py-2 rounded-xl bg-[#0F58B6] hover:bg-[#0c4897] text-white text-xs font-bold shadow-md shadow-blue-500/20 transition-all active:scale-95 cursor-pointer whitespace-nowrap"
                    >
                      <Plus className="w-4 h-4" />
                      <span>Log Custom Visit</span>
                    </button>
                  )}
                </div>
              </div>

              {/* Collapsible New Visit Form */}
              {isAddingVisit && (
                <form
                  id="doctor-visit-form"
                  onSubmit={(e) => {
                    e.preventDefault();
                    const currentTarget = activeRx || prescription;
                    if (!currentTarget) return;
                    const docName = visitDoctor.trim() || currentTarget.doctorName || 'Doctor';
                    const updated = addDoctorVisitToPrescription(currentTarget.id, {
                      prescriptionId: currentTarget.id,
                      visitDate: visitDate || new Date().toISOString().split('T')[0],
                      doctorName: docName,
                      clinicOrHospital: visitClinic.trim() || currentTarget.clinicOrHospital || undefined,
                      reasonForVisit: visitReason.trim() || undefined,
                      diagnosis: visitDiagnosis.trim() || undefined,
                      vitals:
                        visitBp || visitPulse || visitWeight || visitTemp
                          ? {
                              bloodPressure: visitBp.trim() || undefined,
                              pulse: visitPulse.trim() || undefined,
                              weight: visitWeight.trim() || undefined,
                              temperature: visitTemp.trim() || undefined,
                            }
                          : undefined,
                      clinicalNotes: visitNotes.trim() || undefined,
                      nextFollowUpDate: visitFollowUp || undefined,
                    });
                    if (updated) {
                      setActiveRx(updated);
                      if (onUpdate) onUpdate(updated);
                    }
                    setIsAddingVisit(false);
                    setVisitReason('');
                    setVisitBp('');
                    setVisitPulse('');
                    setVisitWeight('');
                    setVisitTemp('');
                    setVisitNotes('');
                    setVisitFollowUp('');
                  }}
                  className="p-5 sm:p-6 rounded-2xl bg-blue-50/40 border border-blue-200/80 space-y-4 shadow-sm animate-in fade-in duration-200"
                >
                  <div className="flex items-center justify-between border-b border-blue-200/60 pb-3">
                    <span className="text-xs font-bold text-[#0F58B6] uppercase tracking-wider font-mono flex items-center gap-1.5">
                      <Stethoscope className="w-4 h-4" />
                      <span>Record Doctor Consultation</span>
                    </span>
                    <button
                      type="button"
                      onClick={() => setIsAddingVisit(false)}
                      className="text-xs text-slate-500 hover:text-slate-800 font-semibold"
                    >
                      Cancel
                    </button>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                    <div>
                      <label className="block text-slate-700 font-bold mb-1">Visit Date *</label>
                      <input
                        type="date"
                        id="visit-date-input"
                        required
                        value={visitDate}
                        onChange={(e) => setVisitDate(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl bg-white border border-slate-300 text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                      />
                    </div>
                    <div>
                      <label className="block text-slate-700 font-bold mb-1">Doctor Name *</label>
                      <input
                        type="text"
                        id="visit-doctor-input"
                        required
                        placeholder="e.g. Dr. Sarah Jenkins"
                        value={visitDoctor}
                        onChange={(e) => setVisitDoctor(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl bg-white border border-slate-300 text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                      />
                    </div>
                    <div>
                      <label className="block text-slate-700 font-bold mb-1">Clinic / Hospital</label>
                      <input
                        type="text"
                        id="visit-clinic-input"
                        placeholder="e.g. Apollo Hospital"
                        value={visitClinic}
                        onChange={(e) => setVisitClinic(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl bg-white border border-slate-300 text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                    <div>
                      <label className="block text-slate-700 font-bold mb-1">Reason for Visit / Symptoms</label>
                      <input
                        type="text"
                        id="visit-reason-input"
                        placeholder="e.g. Routine follow-up, persistent cough, fever"
                        value={visitReason}
                        onChange={(e) => setVisitReason(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl bg-white border border-slate-300 text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                      />
                    </div>
                    <div>
                      <label className="block text-slate-700 font-bold mb-1">Diagnosis / Assessment</label>
                      <input
                        type="text"
                        id="visit-diagnosis-input"
                        placeholder="e.g. Upper respiratory tract infection"
                        value={visitDiagnosis}
                        onChange={(e) => setVisitDiagnosis(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl bg-white border border-slate-300 text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                      />
                    </div>
                  </div>

                  {/* Vitals Recording Grid */}
                  <div className="pt-1">
                    <p className="text-[11px] font-mono text-slate-600 font-bold uppercase mb-2">Recorded Vitals</p>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                      <div>
                        <label className="block text-[11px] text-slate-600 mb-0.5">Blood Pressure</label>
                        <input
                          type="text"
                          id="visit-bp-input"
                          placeholder="e.g. 120/80 mmHg"
                          value={visitBp}
                          onChange={(e) => setVisitBp(e.target.value)}
                          className="w-full px-2.5 py-1.5 rounded-lg bg-white border border-slate-300 text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                        />
                      </div>
                      <div>
                        <label className="block text-[11px] text-slate-600 mb-0.5">Pulse Rate</label>
                        <input
                          type="text"
                          id="visit-pulse-input"
                          placeholder="e.g. 74 bpm"
                          value={visitPulse}
                          onChange={(e) => setVisitPulse(e.target.value)}
                          className="w-full px-2.5 py-1.5 rounded-lg bg-white border border-slate-300 text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                        />
                      </div>
                      <div>
                        <label className="block text-[11px] text-slate-600 mb-0.5">Body Weight</label>
                        <input
                          type="text"
                          id="visit-weight-input"
                          placeholder="e.g. 68 kg"
                          value={visitWeight}
                          onChange={(e) => setVisitWeight(e.target.value)}
                          className="w-full px-2.5 py-1.5 rounded-lg bg-white border border-slate-300 text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                        />
                      </div>
                      <div>
                        <label className="block text-[11px] text-slate-600 mb-0.5">Temperature</label>
                        <input
                          type="text"
                          id="visit-temp-input"
                          placeholder="e.g. 98.6 °F"
                          value={visitTemp}
                          onChange={(e) => setVisitTemp(e.target.value)}
                          className="w-full px-2.5 py-1.5 rounded-lg bg-white border border-slate-300 text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                        />
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                    <div className="sm:col-span-2">
                      <label className="block text-slate-700 font-bold mb-1">Clinical Notes &amp; Doctor Advice</label>
                      <textarea
                        id="visit-notes-input"
                        rows={2}
                        placeholder="Doctor's recommendations, dietary advice, lab orders, or medication adjustments..."
                        value={visitNotes}
                        onChange={(e) => setVisitNotes(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl bg-white border border-slate-300 text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-[#0F58B6] resize-none"
                      />
                    </div>
                    <div>
                      <label className="block text-slate-700 font-bold mb-1">Next Follow-Up Date</label>
                      <input
                        type="date"
                        id="visit-followup-input"
                        value={visitFollowUp}
                        onChange={(e) => setVisitFollowUp(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl bg-white border border-slate-300 text-slate-800 font-medium focus:outline-none focus:ring-2 focus:ring-[#0F58B6]"
                      />
                    </div>
                  </div>

                  <div className="flex items-center justify-end gap-2 pt-2 border-t border-blue-200/60">
                    <button
                      type="button"
                      onClick={() => setIsAddingVisit(false)}
                      className="px-4 py-2 rounded-xl bg-white border border-slate-300 hover:bg-slate-100 text-slate-700 text-xs font-bold transition-all cursor-pointer"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      id="btn-save-visit"
                      className="px-4 py-2 rounded-xl bg-[#0F58B6] hover:bg-[#0c4897] text-white text-xs font-bold shadow-md shadow-blue-500/20 transition-all cursor-pointer"
                    >
                      Save Visit Log
                    </button>
                  </div>
                </form>
              )}

              {/* Visit Timeline List */}
              {(!(activeRx || prescription)?.doctorVisits || (activeRx || prescription)!.doctorVisits!.length === 0) ? (
                <div className="p-8 text-center rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
                  <Stethoscope className="w-10 h-10 text-slate-300 mx-auto" />
                  <div>
                    <p className="text-sm font-semibold text-slate-700">No Doctor Visits Logged</p>
                    <p className="text-xs text-slate-500 mt-0.5">
                      Keep a complete chronological history of each doctor visit, vitals, and physician advice.
                    </p>
                  </div>
                  <div className="pt-2 flex items-center justify-center gap-3 flex-wrap">
                    <button
                      type="button"
                      id="btn-auto-extract-empty"
                      onClick={() => {
                        const cur = activeRx || prescription;
                        if (cur) {
                          const updated = autoGenerateDoctorVisitForPrescription(cur.id);
                          if (updated) {
                            setActiveRx(updated);
                            if (onUpdate) onUpdate(updated);
                          }
                        }
                      }}
                      className="px-4 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold shadow-md shadow-purple-500/20 inline-flex items-center gap-1.5 cursor-pointer transition-all active:scale-95"
                    >
                      <Sparkles className="w-4 h-4" />
                      <span>Auto-Generate from Prescription</span>
                    </button>

                    <button
                      type="button"
                      id="btn-log-first-visit"
                      onClick={() => {
                        const cur = activeRx || prescription;
                        setVisitDoctor(cur?.doctorName || '');
                        setVisitClinic(cur?.clinicOrHospital || '');
                        setVisitDate(cur?.date || new Date().toISOString().split('T')[0]);
                        setVisitDiagnosis(cur?.diagnosis || '');
                        setVisitNotes(cur?.notes || '');
                        setVisitFollowUp(cur?.followUpDate || '');
                        setIsAddingVisit(true);
                      }}
                      className="px-4 py-2 rounded-xl bg-white border border-slate-300 hover:bg-slate-100 text-slate-700 text-xs font-bold inline-flex items-center gap-1.5 cursor-pointer transition-all active:scale-95"
                    >
                      <Plus className="w-4 h-4 text-blue-600" />
                      <span>Log Custom Visit Manually</span>
                    </button>
                  </div>
                </div>
              ) : (
                <div className="space-y-4" id="doctor-visits-timeline">
                  {((activeRx || prescription)!.doctorVisits || [])
                    .slice()
                    .sort((a, b) => (b.visitDate || '').localeCompare(a.visitDate || ''))
                    .map((visit) => (
                      <div
                        key={visit.id}
                        id={`doctor-visit-card-${visit.id}`}
                        className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-3 shadow-sm hover:border-blue-300/80 transition-all"
                      >
                        {/* Visit Card Header */}
                        <div className="flex flex-wrap items-start justify-between gap-2 border-b border-slate-200/80 pb-3">
                          <div>
                            <div className="flex items-center gap-2">
                              <span className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
                                <User className="w-3.5 h-3.5 text-[#0F58B6]" />
                                <span>{visit.doctorName}</span>
                              </span>
                              {visit.clinicOrHospital && (
                                <span className="text-[11px] px-2 py-0.5 rounded-full bg-slate-200/60 text-slate-700 font-medium">
                                  {visit.clinicOrHospital}
                                </span>
                              )}
                              {visit.isAutoGenerated && (
                                <span className="text-[10px] px-2 py-0.5 rounded-full bg-purple-50 text-purple-700 border border-purple-200 font-medium flex items-center gap-1">
                                  <Sparkles className="w-3 h-3 text-purple-500" />
                                  <span>Auto from Rx</span>
                                </span>
                              )}
                            </div>
                            {visit.reasonForVisit && (
                              <p className="text-xs text-slate-600 mt-1 font-medium">
                                <span className="font-semibold text-slate-700">Reason: </span>
                                {visit.reasonForVisit}
                              </p>
                            )}
                          </div>

                          <div className="flex items-center gap-2">
                            <span className="text-xs px-2.5 py-1 rounded-xl bg-blue-50 text-[#0F58B6] border border-blue-200 font-mono font-bold flex items-center gap-1">
                              <Calendar className="w-3 h-3" />
                              <span>{visit.visitDate}</span>
                            </span>
                            <button
                              type="button"
                              id={`delete-visit-${visit.id}`}
                              onClick={() => {
                                const cur = activeRx || prescription;
                                if (cur) {
                                  const updated = deleteDoctorVisitFromPrescription(cur.id, visit.id);
                                  if (updated) {
                                    setActiveRx(updated);
                                    if (onUpdate) onUpdate(updated);
                                  }
                                }
                              }}
                              className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition-colors cursor-pointer"
                              title="Delete visit record"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </div>

                        {/* Vitals Badges (if any) */}
                        {visit.vitals && Object.values(visit.vitals).some(Boolean) && (
                          <div className="flex flex-wrap items-center gap-2 pt-1">
                            {visit.vitals.bloodPressure && (
                              <span className="text-xs px-2.5 py-1 rounded-lg bg-red-50 text-red-700 border border-red-200/60 font-mono flex items-center gap-1">
                                <Heart className="w-3 h-3 text-red-500" />
                                <span>BP: {visit.vitals.bloodPressure}</span>
                              </span>
                            )}
                            {visit.vitals.pulse && (
                              <span className="text-xs px-2.5 py-1 rounded-lg bg-pink-50 text-pink-700 border border-pink-200/60 font-mono flex items-center gap-1">
                                <Activity className="w-3 h-3 text-pink-500" />
                                <span>Pulse: {visit.vitals.pulse}</span>
                              </span>
                            )}
                            {visit.vitals.weight && (
                              <span className="text-xs px-2.5 py-1 rounded-lg bg-indigo-50 text-indigo-700 border border-indigo-200/60 font-mono flex items-center gap-1">
                                <span>Weight: {visit.vitals.weight}</span>
                              </span>
                            )}
                            {visit.vitals.temperature && (
                              <span className="text-xs px-2.5 py-1 rounded-lg bg-amber-50 text-amber-700 border border-amber-200/60 font-mono flex items-center gap-1">
                                <Thermometer className="w-3 h-3 text-amber-500" />
                                <span>Temp: {visit.vitals.temperature}</span>
                              </span>
                            )}
                          </div>
                        )}

                        {/* Diagnosis & Clinical Notes */}
                        {visit.diagnosis && (
                          <p className="text-xs text-slate-800">
                            <span className="font-bold text-slate-700">Diagnosis: </span>
                            {visit.diagnosis}
                          </p>
                        )}

                        {visit.clinicalNotes && (
                          <div className="p-3 rounded-xl bg-white border border-slate-200/90 text-xs text-slate-700 space-y-1">
                            <p className="text-[10px] font-mono text-slate-500 uppercase font-bold">Doctor Advice &amp; Clinical Directives</p>
                            <p className="leading-relaxed font-medium">{visit.clinicalNotes}</p>
                          </div>
                        )}

                        {visit.nextFollowUpDate && (
                          <div className="flex items-center gap-1.5 text-xs text-emerald-700 font-semibold pt-1">
                            <Clock className="w-3.5 h-3.5 text-emerald-600" />
                            <span>Next Scheduled Follow-Up: {visit.nextFollowUpDate}</span>
                          </div>
                        )}
                      </div>
                    ))}
                </div>
              )}
            </div>
          )}

          {/* TAB 4: MULTI-LANGUAGE VOICE EXPLAINER (SARVAM AI + GEMINI) */}
          {activeView === 'explain' && (
            <div className="space-y-6 max-w-3xl mx-auto py-2">
              {/* Non-Blocking Fallback Toast / Banner */}
              {fallbackToast && (
                <div className="flex items-center justify-between p-3.5 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900 text-xs font-medium shadow-sm animate-in fade-in slide-in-from-top-2 duration-200">
                  <div className="flex items-center gap-2.5">
                    <AlertCircle className="w-4 h-4 text-amber-600 flex-shrink-0" />
                    <span>{fallbackToast}</span>
                  </div>
                  <button
                    type="button"
                    onClick={() => setFallbackToast(null)}
                    className="text-amber-700 hover:text-amber-900 text-xs font-bold ml-3 cursor-pointer"
                  >
                    Dismiss
                  </button>
                </div>
              )}

              {/* Hero Audio Controls Card */}
              <div className="p-6 sm:p-7 rounded-3xl bg-gradient-to-br from-[#0F58B6] via-indigo-600 to-blue-900 text-white shadow-xl shadow-blue-600/20 relative overflow-hidden">
                <div className="relative z-10 space-y-5">
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <div className="flex items-center gap-2">
                      <span className="px-3 py-1 rounded-full text-[11px] font-bold bg-white/20 backdrop-blur-md text-white border border-white/20 flex items-center gap-1.5">
                        <Sparkles className="w-3.5 h-3.5 text-amber-300" />
                        AI Voice Translation
                      </span>
                      <span className="px-3 py-1 rounded-full text-[11px] font-bold bg-emerald-400/20 text-emerald-200 border border-emerald-400/30 font-mono">
                        Sarvam AI TTS
                      </span>
                    </div>

                    {isSpeakingAudio && (
                      <div className="flex items-center gap-2 px-3.5 py-1 rounded-full bg-white/20 backdrop-blur-md text-white text-xs font-semibold animate-pulse">
                        <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
                        <span>Playing Audio...</span>
                      </div>
                    )}
                  </div>

                  <div>
                    <h3 className="text-xl sm:text-2xl font-black tracking-tight text-white">
                      Understand Your Prescription
                    </h3>
                    <p className="text-xs sm:text-sm text-blue-100 mt-1 max-w-xl leading-relaxed">
                      Listen to clear, everyday spoken instructions in your native language explaining what each medicine does, when to take it, and for how long.
                    </p>
                  </div>

                  {/* Language Selector 4-Pill Bar */}
                  <div className="space-y-2 pt-1">
                    <p className="text-[11px] font-mono text-blue-200 uppercase font-bold tracking-wider">
                      Select Target Voice Language:
                    </p>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
                      {[
                        { code: 'en' as ExplainerLanguage, label: 'English', sub: 'en-IN' },
                        { code: 'te' as ExplainerLanguage, label: 'తెలుగు', sub: 'Telugu' },
                        { code: 'hi' as ExplainerLanguage, label: 'हिन्दी', sub: 'Hindi' },
                        { code: 'ta' as ExplainerLanguage, label: 'தமிழ்', sub: 'Tamil' },
                      ].map((lang) => {
                        const isSelected = explainerLang === lang.code;
                        return (
                          <button
                            key={lang.code}
                            type="button"
                            onClick={() => handleSelectLanguage(lang.code)}
                            className={`p-3 rounded-2xl flex flex-col items-center justify-center transition-all cursor-pointer ${
                              isSelected
                                ? 'bg-white text-blue-950 shadow-lg font-bold scale-[1.02]'
                                : 'bg-white/10 hover:bg-white/15 text-white border border-white/15 font-semibold active:scale-95'
                            }`}
                          >
                            <span className="text-sm font-bold tracking-tight">{lang.label}</span>
                            <span className={`text-[10px] font-mono ${isSelected ? 'text-blue-700' : 'text-blue-200'}`}>
                              {lang.sub}
                            </span>
                          </button>
                        );
                      })}
                    </div>
                  </div>

                  {/* Playback Controls & Audio Bar */}
                  <div className="pt-2 flex flex-wrap items-center gap-3">
                    <button
                      type="button"
                      id="play-voice-explanation-btn"
                      onClick={handleToggleSpeech}
                      disabled={isGeneratingExplanation}
                      className={`px-6 py-3.5 rounded-2xl text-xs sm:text-sm font-bold transition-all shadow-lg flex items-center gap-2.5 cursor-pointer active:scale-95 ${
                        isSpeakingAudio
                          ? 'bg-rose-500 hover:bg-rose-600 text-white shadow-rose-500/30'
                          : 'bg-emerald-500 hover:bg-emerald-600 text-white shadow-emerald-500/30'
                      }`}
                    >
                      {isGeneratingExplanation ? (
                        <>
                          <Loader2 className="w-4 h-4 animate-spin" />
                          <span>Gemini Translating...</span>
                        </>
                      ) : isSpeakingAudio ? (
                        <>
                          <Square className="w-4 h-4 fill-white" />
                          <span>Stop Audio</span>
                        </>
                      ) : (
                        <>
                          <Volume2 className="w-4 h-4" />
                          <span>{explanationText ? 'Play Audio' : 'Explain & Listen'}</span>
                        </>
                      )}
                    </button>

                    {explanationText && (
                      <button
                        type="button"
                        onClick={handleCopyExplanation}
                        className="px-4 py-3.5 rounded-2xl bg-white/15 hover:bg-white/25 text-white border border-white/20 text-xs font-bold transition-all flex items-center gap-2 cursor-pointer active:scale-95"
                        title="Copy plain explanation text"
                      >
                        {copiedExplanation ? (
                          <>
                            <Check className="w-3.5 h-3.5 text-emerald-300" />
                            <span>Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" />
                            <span>Copy Transcript</span>
                          </>
                        )}
                      </button>
                    )}
                  </div>
                </div>
              </div>

              {/* Readable Explanation Transcript Card */}
              <div className="p-6 rounded-3xl bg-white border border-slate-200 shadow-sm space-y-4">
                <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                  <div className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-blue-600" />
                    <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider font-mono">
                      Spoken Script Transcript ({explainerLang.toUpperCase()})
                    </h4>
                  </div>
                  <span className="text-[11px] px-2.5 py-0.5 rounded-full bg-blue-50 text-blue-700 font-mono font-bold border border-blue-100">
                    {explainerLang === 'en' ? 'English' : explainerLang === 'te' ? 'Telugu' : explainerLang === 'hi' ? 'Hindi' : 'Tamil'}
                  </span>
                </div>

                {isGeneratingExplanation ? (
                  <div className="py-12 text-center space-y-3">
                    <Loader2 className="w-8 h-8 text-blue-600 animate-spin mx-auto" />
                    <p className="text-xs font-semibold text-slate-700">
                      Formulating everyday explanation in {explainerLang === 'en' ? 'English' : explainerLang === 'te' ? 'Telugu' : explainerLang === 'hi' ? 'Hindi' : 'Tamil'}...
                    </p>
                    <p className="text-[11px] text-slate-400">
                      Translating dosages, frequencies, and food directions into simple patient guidance.
                    </p>
                  </div>
                ) : explanationText ? (
                  <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200/80">
                    <p className="text-sm sm:text-base text-slate-800 leading-relaxed font-medium whitespace-pre-line">
                      {explanationText}
                    </p>
                  </div>
                ) : (
                  <div className="py-12 text-center space-y-2 text-slate-400">
                    <Volume2 className="w-10 h-10 mx-auto text-slate-300" />
                    <p className="text-xs font-semibold text-slate-600">No Audio Generated Yet</p>
                    <p className="text-[11px] text-slate-400 max-w-sm mx-auto">
                      Select your language above and click &quot;Explain &amp; Listen&quot; to synthesize this prescription into speech.
                    </p>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
