import mongoose, { Schema } from 'mongoose';
import { Prescription as IPrescription, Medication } from '@/types/prescription';

const MedicationSchema = new Schema<Medication>(
  {
    id: { type: String, required: true },
    name: { type: String, required: true },
    genericName: { type: String },
    dosage: { type: String, default: 'As directed' },
    frequency: { type: String, default: 'Daily' },
    route: { type: String },
    timing: { type: String, default: 'anytime' },
    specific_time: { type: String },
    flagged_for_review: { type: Boolean },
    duration: { type: String },
    instructions: { type: String },
    remainingPills: { type: Number },
    totalPrescribedPills: { type: Number },
    refillThreshold: { type: Number },
  },
  { _id: false }
);

const DoctorVisitSchema = new Schema(
  {
    id: { type: String, required: true },
    prescriptionId: { type: String, required: true },
    visitDate: { type: String, required: true },
    doctorName: { type: String, required: true },
    clinicOrHospital: { type: String },
    reasonForVisit: { type: String },
    diagnosis: { type: String },
    vitals: {
      bloodPressure: { type: String },
      pulse: { type: String },
      weight: { type: String },
      temperature: { type: String },
    },
    clinicalNotes: { type: String },
    treatmentPlan: { type: String },
    nextFollowUpDate: { type: String },
    nextFollowUpCompleted: { type: Boolean, default: false },
    isAutoGenerated: { type: Boolean, default: false },
    createdAt: { type: String, default: () => new Date().toISOString() },
  },
  { _id: false }
);

const PrescriptionSchema = new Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    userId: { type: String, index: true },
    title: { type: String, required: true },
    doctorName: { type: String },
    clinicOrHospital: { type: String },
    patientName: { type: String },
    familyMember: { type: String, default: 'self', index: true },
    patientRelation: { type: String },
    date: { type: String, default: () => new Date().toISOString().split('T')[0] },
    uploadedAt: { type: String },
    diagnosis: { type: String },
    medications: { type: [MedicationSchema], default: [] },
    notes: { type: String },
    followUpDate: { type: String },
    followUpCompleted: { type: Boolean, default: false },
    followUpCompletedAt: { type: String },
    rawText: { type: String },
    fileUrl: { type: String },
    fileName: { type: String },
    fileType: { type: String, default: 'image' },
    fileSize: { type: Number },
    createdAt: { type: String, default: () => new Date().toISOString() },
    status: { type: String, default: 'active' },
    doctorVisits: { type: [DoctorVisitSchema], default: [] },
    explanations: { type: Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
  }
);

// Compound indexes for high-throughput multi-tenant querying and sorting
PrescriptionSchema.index({ userId: 1, createdAt: -1 });
PrescriptionSchema.index({ userId: 1, date: -1 });
PrescriptionSchema.index({ userId: 1, familyMember: 1, createdAt: -1 });

export const PrescriptionModel =
  mongoose.models.Prescription || mongoose.model<IPrescription>('Prescription', PrescriptionSchema);

export default PrescriptionModel;
